/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('96419','33261','1','Einmalige Luxusvilla mit Panoramablick im Südwesten Mallorcas'),
('96420','33262','1','In einmaliger Lage, mit Blick auf die Süd Westküste Mallorcas, von Portals Nous bis Palma Nova, liegt die in den 90er Jahren erstellt Luxus Villa. Sie wurde mit hochwertigen Materialien erstellt und bietet Platz bis zu 14 Personen. Über den Eingang im Erdgeschoss betritt man eine große Einganshalle mit Salon. Auf dieser Ebene befinden sich noch eine Garderobe, Gäste WC, Büroraum, Wäscheraum, Fitnessraum, Salon mit Kamin (ca 70m²), großzügiger Wohn-Essraum mit offener Küche, Speisekammer,  2. Gäste WC sowie begehbare Kühlzelle. Im 1. OG sind neben dem Hauptschlafzimmer mit 2 Ankleiden ein Badezimmer und eine Terrasse auch noch 6 Gäste Schlafzimmer (davon 5 mit Badezimmern en suite). Der uneinsehbare Gartenbereich, mit seinen offenen und überdachten Terrassen und einem großen  Pool, lädt zu feiern oder relaxen ein. Im Poolhaus hat es noch einen Waschmaschinen Raum und ein Badezimmer mit WC und Dusche. Zur  hochwertigen Ausstattung gehören u.a. ein Aufzug, eine Fußbodenheizung (Öl / Wasser), Klimaanlage w/k und Holz Doppelglasfenster. 3 Autos finden Platz unter einem Carport oder auf weiteren offenen Stellplätzen.Die Villa befindet sich in einem Top Zustand und eignet sich auch für ganzjähriges bewohnen'),
('96421','33263','1',Null),
('96422','33264','1',Null),
('96423','33265','1',Null),
('96424','33266','1',Null),
('96425','33267','1',Null),
('96427','33261','5','Unique luxury villa with panoramic views in the southwest of Mallorca'),
('96428','33262','5','In a unique location, overlooking the south west coast of Majorca,  from Portals Nous to Palma Nova, this Villa was built in the 90ies with high quality materials. This estate can accommodate up to 14 people. Over the entrance on the ground floor you  enter a large entrance hall witha big reception salon. At this level there are a wardrobe,a guest toilet, an office, laundry room, exercise room, lounge with fireplace (approx 70sqm), spacious living room with open kitchen, pantry, 2. guest toilet and walk-in cold room. On the 1st floor are the master bedroom with 2 dressing rooms, a bathroom and a terrace. Here are also 6 guest bedrooms (5 with en-suite bathrooms). The secluded garden area, with its open and covered terraces and a large pool invites to celebrate or relax. In the pool house there is a washmachine room and a bathroom with toilet and shower. The high-quality facilities includes among others a lift, underfloor heating (oil / water), air-conditioning w / c and double glazed wooden windows. 3 cars can be parked under a carport or on other open parking spaces. The villa is in excellent condition and is also suitable for all year-round occupancy'),
('96429','33263','5',Null),
('96430','33264','5',Null),
('96431','33265','5',Null),
('96432','33266','5',Null),
('96433','33267','5',Null),
('96435','33261','22','Villa de lujo con vistas panorámicas en el suroeste de Mallorca'),
('96436','33262','22','En una ubicación única, con vistas a la costa suroeste de Mallorca, de Portals Nous hasta Palma Nova. Esta villa se ha creado en los 90s con materiales de alta calidad y tiene capacidad para hasta 14 personas. Sobre la entrada en la planta baja se entra en un gran hall de entrada con sala de estar. En este nivel hay tambien un ropero, aseo,  oficina, sala de lavandería, gimnasio, sala de estar con chimenea (70m² aprox), amplio salón - comedor con cocina abierta, despensa, 2. aseo de invitados y  walk-in cámara frigorífica. En la primera planta se encuentran al lado del dormitorio principal con 2 vestidores, un baño y una terraza,  6 dormitorios de invitados (5 con cuarto de baño en siute). La zona de jardín privado, con sus terrazas abiertas y cubiertas y una gran piscina invita a celebrar o relajarse. En la casa de la piscina hay un lavadero y un baño conaseo y ducha. Instalaciones de alta calidad incluyen entre otros: ascensor, calefacción por suelo radiante (aceite / agua), aire acondicionado f / c, ventanas de doble acristalamiento de madera y mas. 3 coches encontraron espacio bajo una cochera o en otros espacios abiertos.  La villa se encuentra en excelentes condiciones y también es adecuado para su ocupación durante todo el año.'),
('96437','33263','22',Null),
('96438','33264','22',Null),
('96439','33265','22',Null),
('96440','33266','22',Null),
('96441','33267','22',Null),
('96443','33269','1',Null),
('96444','33270','1',Null),
('96445','33271','1',Null),
('96446','33272','1',Null);
