/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('95765','33034','22','1985'),
('95766','33034','5','1985'),
('95767','33034','1','1985'),
('95768','33035','1','Großzügige Dublexwohnung mit Hafenblick, Palma de Mallorca'),
('95769','33036','1','Nur wenige Gehminuten vom Einkaufszentrum Porto Pi in Palma de Mallorca entfernt, befindet sich dieses geräumige Penthouse-Dublex-Apartment. Auf der unteren Ebene der Wohnung befindet sich der Eingang mit Diele, Wohn-Esszimmer, Terrasse, große Küche mit Hauswirtschaftsraum und Abstellraum, 1 Gästeschlafzimmer mit Bad en suite und ein Gäste WC. In der oberen Etage hat es eine Galerie, 2 Schlafzimmer mit je einem Badezimmer en suite, sowie das Hauptschlafzimmer mit Badezimmer und einer Terrasse. Zur gepflegten Ausstattung gehören Marmor Fußböden, Parkettboden in den Schlafzimmern, Gas Zentralheizung, Klimaanlage, Alu- Doppelglasfenster und eine Einbauküche mit Esstisch. Bequemes Parken in der Tiefgarage mit eigenem Abstellplatz ist möglich. \r\nVor dem Apartmentgebäude liegt der Gemeinschaftsgarten mit Pool und Zugang zu einem kleinen Sportboothafen. Liegeplätze für kleinere Sportboote sind sehr gefragt. Der Verkäufer würde sein Boot, eine Sunseeker Monte Rey 27 (7,90m lang) 2 Volvo Motoren Gasolin,  für 18.500€ verkaufen. Der Liegeplatz kann von der Stadt Palma für ca 650€ / Jahr dazugemietet werden. \r\n'),
('95770','33037','1',Null),
('95771','33038','1',Null),
('95772','33039','1',Null),
('95773','33040','1',Null),
('95774','33041','1',Null),
('95776','33043','1',Null),
('95777','33044','1',Null),
('95778','33045','1',Null),
('95779','33035','5','Generous Dublexwohnung with Harbour View, Palma de Mallorca'),
('95780','33036','5','Located a short walk from the Porto Pi shopping center in Palma de Mallorca away, you will find this spacious penthouse dublex apartment on the 6th and 7th floor. On the lower level of the apartment is the entrance with entrance hall, living-dining room, large kitchen with utility room and storage room, 1 guest bedroom with bathroom en suite and a guest toilet. The upper floor has a gallery, 2 bedrooms each with a bathroom en suite and the master bedroom with bathroom and a terrace. The apartment is equiped with marble floors, parquet floor in the bedrooms, gas central heating, air conditioning, aluminum double glazed windows and a fitted kitchen with dining table. Convenient parking in the underground garage with private parking space is possible.Front of the apartment building there is a comunity Pool and acces to a small marina. Boat moorings for small pleasure boats are in great demand. The seller would be sell his boat, a Sunseeker Monte Rey 27 (7,90m long),equiped with 2 Volvo engines gasoline for € 18,500. The berth can be rented from the city of Palma for about € 650 / year.'),
('95781','33037','5',Null),
('95782','33038','5',Null),
('95783','33039','5',Null),
('95784','33040','5',Null),
('95785','33041','5',Null),
('95787','33035','22','Generoso Dublexwohnung con vistas al puerto de Palma de Mallorca'),
('95788','33036','22','Situado a pocos pasos del centro comercial Porto Pi, en Palma de Mallorca, se encuentra este amplio apartamento duplex ático. En la planta baja de la vivienda es la entrada con hall de entrada, salón-comedor, amplia cocina con lavadero y trastero, 1 dormitorio de invitados con baño en suite y un aseo. La planta superior tiene una galería, 2 dormitorios cada uno con baño en suite y el dormitorio principal con baño y una terraza. El apartamento esta equipado con  materiales de primera qualidad como: suelos de mármol, suelos de parquet en los dormitorios, calefacción central de gas, aire acondicionado, ventanas de aluminio de doble acristalamiento y una cocina equipada con mesa de comedor. Cómodo aparcamiento en el garaje subterráneo con 1 plaza de coche privada esta possible\r\nFrente del edificio de apartamentos hay un jardin con piscina cumunitaria y accseso a un pequeño puerto deportivo. Amarres de barcos para las pequeñas embarcaciones de recreo están en gran demanda. El vendedor puede tambien vender su barco,un Sunseeker Monte Rey 27 (7,90m de largo) con 2 Motores Volvo-gasolina, por € 18.500. El amarradero se puede alquilar desde la ciudad de Palma de unos 650 € / año\r\n'),
('95789','33037','22',Null),
('95790','33038','22',Null),
('95791','33039','22',Null),
('95792','33040','22',Null),
('95793','33041','22',Null),
('95795','33043','5',Null),
('95796','33044','5',Null),
('95797','33045','5',Null),
('95798','33043','22',Null),
('95799','33044','22',Null),
('95800','33045','22',Null);
