/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('92978','32018','1','Außergewöhnlich preiswert!! Ehemaliges 4 Sterne Finca Hotel im Herzen von Mallorca'),
('92979','32019','1','Das Anwesen aus dem Jahr 1879 steht auf einem ca 54.200m² großen, flachen Grundstück im Herzen von Mallorca gelegen. Nach Palma de Mallorca und dem Flughafen sind es nur 30 Min. Das sehr solide gebaute ehemalige Weingut wurde 1990 zum 4 Sterne Finca Hotel ausgebaut und bis 2010 betrieben. Seit dem steht das schöne Anwesen leer und benötigt einen neuen Betreiber, der dem schmucken Hotel wieder Leben einhaucht.  Das Hotel bietet im Haupthaus eine Rezeption, Restaurant, großer Wintergarten / Restaurant, großer Veranstaltungssaal mit 15m hoher Gewölbedecke (ehemaliges Weinlager), Küche ect.\r\nIn den oberen Etagen befinden sich 5 geräumige Suiten und Personal Unterkünfte. 21 großzugige Juniorsuiten sowie ein Hallenbad mit Sauna liegen in einen Nebengebäude. Auf dem ca 54.000m² großen Grundstück hat es außer großen  Auto Parkflächen auch noch ein Außenpool mit Liegeterrassen, Allwetter- Tennisplatz und ein 9 Loch Pitch & Putt Golfplatz, der leider ein wenig eingewachsen ist. Ansonsten ein sehr interessantes Objekt das mit wenig Aufwand wieder im alten Glanz erscheinen könnte. Der Verkaufspreis wurde von 5,500.000 auf 2.900.000€ gesenkt, um dem neuen Eigentümer mit den anfallenden Instandsetzungskosten entgegenzukommen.\r\n'),
('92980','32020','1',Null),
('92981','32021','1',Null),
('92982','32022','1',Null),
('92983','32023','1',Null),
('92984','32024','1',Null),
('92986','32018','5','Exeptional low price!! Former 4 star country house hotel in the heart of Mallorca '),
('92987','32019','5','The property dating back to 1879 and stands on a ca 54.200m² large flat plot located in the heart of Mallorca. Palma de Mallorca and the airport is only 30 min. away. The very solidly built former winery was expanded and reformed in 1990 to 4 star country house hotel and operated until 2010. Since is the beautiful property empty and needs a new operator, again breathes life into this pretty hotel.  The hotel offers a reception in the main building, restaurant, large winter garden / restaurant, large ceremonial hall with 15m high vaulted ceiling (former wine warehouse), kitchen ect. \r\nIn the upper floors there are 5 spacious suites and staff accommodations. 21 large junior suites and an indoor pool with sauna are located in a neighboring building. On the ca 54.000m² large property you find a large car parking areas also an outdoor swimming pool with sun terraces, all-weather tennis court and a 9 hole pitch and putt golf course, which is unfortunately a little over grown. A large room for bicycles and bicycle service or massages is available. Currently, the expandability for more hotel rooms will be checked at the Building Department. A very interesting country house hotel, which could appear with little effort back to its former glory.\r\nThe sale price is lowered from 5,500.000  to 2,900.000 € to accommodate to the new owner with the resulting repair costs.\r\n'),
('92988','32020','5',Null),
('92989','32021','5',Null),
('92990','32022','5',Null),
('92991','32023','5',Null),
('92992','32024','5',Null),
('92994','32018','22','Valor exepcional!!! Hotel rural de 4 estrellas en el corazón de Mallorca '),
('92995','32019','22','La propiedad data de 1879 se encuentra en una gran parcela plana de 54.200m² situado en el corazón de Mallorca. Palma de Mallorca y el aeropuerto está a sólo 30 min. La antigua bodega muy sólidamente construido se amplió en 1990 a 4 estrellas hotel de campo y funcionó hasta 2010. Desde es la hermosa propiedad vacía y necesita un nuevo operador, de nuevo se respira la vida en este bonito hotel.  El hotel ofrece una recepción en el edificio, restaurante, amplio jardín de invierno / restaurante, gran sala ceremonial principal con 15m de alto techo abovedado (antigua bodega), cocina ect. \r\nEn las plantas superiores hay 5 amplias suites y alojamientos  de personal. 21 grandes junior suites y una piscina cubierta con sauna se encuentran en un edificio vecino. En el ca 54.000m² gran propiedad que tiene, excepto grandes zonas de aparcamiento tambien una piscina exterior con terraza-solarium, pista de tenis y un campo de 9 hoyos y campo de golf (pitch & putt), que es por desgracia un poco crecido. Ademas hay un gran espacio para las bicicletas y servicio de bicicletas o de masajes. Actualmente, la capacidad de expansión para más habitaciones de hotel se puede comprobar en el Departamento de Construcción. Un muy interesante hotel rural, que podría aparecer con poco esfuerzo volver a su antigua gloria.\r\nEl precio de venta se redujo de 5,500.000€ a  2.900.000 € para dar cabida al nuevo propietario con los gastos de reparación que resulten.\r\n'),
('92996','32020','22',Null),
('92997','32021','22',Null),
('92998','32022','22',Null),
('92999','32023','22',Null),
('93000','32024','22',Null),
('93002','32026','22','1879'),
('93003','32026','5','1879'),
('93004','32026','1','1879'),
('93005','32027','1',Null),
('93006','32028','1',Null),
('93007','32029','1',Null),
('93008','32027','5',Null),
('93009','32028','5',Null),
('93010','32029','5',Null),
('93011','32027','22',Null),
('93012','32028','22',Null),
('93013','32029','22',Null);
