/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('41256','14695','1','Einmaliges Anwesen im Landhausstil in Hafennähe von Port d‘Andratx auf 50.000m² Grundstück'),
('41257','14696','1','In einzigartiger Lage über dem Hafen von Port d‘Andratx steht dieses 2007 erbaute Landhaus auf einem 50.000m² großen Grundstück. Von fast allen Zimmern hat man einen fantastischen Meerblick auf die Bucht vom Port d‘Andratx. Das mit Natursteinen verkleidete Anwesen im Landhausstil wurde mit aufwendiger moderner Technik und hochwertigen Materialien liebevoll ausgestattet. Über einen großzügig angelegten Patio erreicht man das Haupthaus mit ca. 945m² konstruierte Fläche. Man betritt das Haupthaus über eine Eingangshalle mit Galerie und erreicht von hier aus ein gemütliches Wohnzimmer mit Kamin sowie ein Esszimmer mit moderner, offener Landhausküche. Ebenso befinden sich auf dieser Ebene ein Gäste-WC mit Dusche, ein Hauswirtschaftsraum, ein Gästetrakt und diverse Terrassen mit integriertem Pool. Im 1.OG befindet sich das Hauptschlafzimmer mit Ankleide und Bad sowie zwei weitere Schlafzimmer und ein Bad. \r\nEin komplettes Apartment mit Wohnzimmer, Schlafzimmer und Bad sowie Terrasse liegt im Untergeschoss. \r\nEine große Garage für 5 Autos plus ein Carport bieten Platz für den Fuhrpark. \r\nElektrische Stromversorgung wird über Photovoltaik und Diesel-Generator gesichert. Anschluss an das örtliche Stromnetz ist möglich.\r\nDie kurze Anbindung zum malerischen Fischerdorf Port d‘Andratx mit seinem Jachthafen und großen kulinarischen Angebot, machen dieses Anwesen einzigartig.\r\nSollten Sie weitere Informationen wünschen, senden Sie uns bitte Ihre Postanschrift und eine Festnetznummer, damit wir Sie direkt kontaktieren können.'),
('41258','14697','1',Null),
('41259','14698','1',Null),
('41260','14699','1',Null),
('41261','14700','1',Null),
('41262','14701','1',Null),
('41264','14695','5','Outstanding property in country house style near the harbor of Port d''Andratx on 50,000 sqm plot '),
('41265','14696','5','Overlooking the harbor of Port d’Andratx this luxury property, built in 2007, sits gloriously on a plot of 50,000 sqm in unique location. From almost every room you can enjoy fantastic sea views to the bay of Port d''Andratx. This mansion with natural stone cladding was finished to highest luxury specifications using only the best materials and latest technical standards available. Passing the spacious patio you will reach the main house with a constructed area of about 945m². The welcoming entrance hall with gallery leads to a cozy living room with fireplace and a dining room with modern, open country kitchen. Furthermore, there you will find a guest bathroom with shower, laundry room, a guest wing and several terraces with pool. The master bedroom with dressing room and bathroom en suite and two further bedrooms and one bathroom are located on the 1st floor. \r\nA separate apartment with living room, bedroom, bathroom and terrace is situated on the ground floor. \r\nA spacious garage  (5 cars) as well as a carport provide sufficient space for big toys.\r\nElectric power supply are realized via photovoltaic and diesel generator. Connection to the local electricity network is possible. \r\nThe immediate vicinity to the picturesque village of Port d''Andratx, with its marina and great dining possibilities, is one of the many amenities of this unique property.\r\nIf you would like to have more information about the property, please send us an email with your postal address and a landline number and we will contact you directly.'),
('41266','14697','5',Null),
('41267','14698','5',Null),
('41268','14699','5',Null),
('41269','14700','5',Null),
('41270','14701','5',Null),
('41272','14695','22','Excepcional mansión cerca del puerto de Port d''Andratx en un terreno de 50.000 m²'),
('41273','14696','22','Construida en el año 2007 esta destacada propiedad de lujo se encuentra en un terreno de 50.000 m² encima del puerto de Port d’Andratx. Desde casi todas las habitaciones se puede disfrutar de unas maravillosas vistas al mar y la bahía de Port d''Andratx. Esta mansión con fachada de piedra natural fue equipada con los materiales de la más alta calidad y la más moderna tecnología. A través de un amplio patio se llega a la casa principal con unos 945 m² de superficie construida. El gran vestíbulo con galería lleva al acogedor salón con chimenea y al comedor con cocina americana. También se encuentra en este nivel, un aseo con ducha, una lavandería, habitaciones para los invitados y varias terrazas con piscina. La planta superior consta del dormitorio principal con vestidor y baño en suite, dos dormitorios y un baño. \r\nAdemás hay un apartamento indepediente con salón, dormitorio, baño y terraza en el sótano. \r\nUn garaje (5 places) más un porche ofrecen suficiente espacio para los coches. \r\nEl suministro eléctrico se realiza a través de paneles fotovoltaicos y un generador de gasóleo. La conexión a la red eléctrica es también posible. \r\nLa proximidad al pintoresco pueblo de Port d''Andratx, con su puerto náutico y sus excelentes restaurantes, es una de las muchas ventajas de esta exclusiva propiedad. Si quiere más información, por favor envíenos un email indicando su dirección postal y un número de teléfono fijo y nos pondrémos en contacto con Usted inmediatamente.\r\n'),
('41274','14697','22',Null),
('41275','14698','22',Null),
('41276','14699','22',Null),
('41277','14700','22',Null),
('41278','14701','22',Null),
('41280','14703','1','2007'),
('41281','14703','5','2007'),
('41282','14703','22','2007'),
('41283','14704','1',Null),
('41284','14705','1',Null),
('41285','14706','1',Null),
('41286','14707','1',Null),
('41287','14705','5',Null),
('41288','14706','5',Null),
('41289','14707','5',Null),
('41290','14704','5',Null),
('41291','14705','22',Null),
('41292','14706','22',Null),
('41293','14707','22',Null),
('41294','14704','22',Null),
('46581','16619','1',Null),
('52027','18447','1',Null),
('52028','18447','5',Null),
('52029','18447','22',Null),
('52030','18448','1',Null),
('52031','18448','5',Null),
('52032','18448','22',Null),
('52033','18449','1',Null),
('52034','18449','5',Null),
('52035','18449','22',Null),
('55095','16619','5',Null),
('55096','16619','22',Null);
