/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('90895','31301','22','Finca con casa de invitados'),
('90896','31302','22','Esta hermosa finca está situada en una zona tranquila, cerca de 26.000 cuadrados de parcela plana en las afueras .....\r\nLa idílica villa de estilo finca, renovada hace unos 7 años se encuentra en las mejores condiciones.\r\nEl aproximadamente 870m² de superficie habitable distribuidos en 3 plantas.\r\nLa planta baja se encuentra un hall de entrada, aseo de invitados, sala de estar, sala de televisión, comedor, 2 dormitorios cada uno con baño en suite y una cocina de campo con isla de cocina y mesa de comedor.\r\nEn la primera planta se encuentran el dormitorio principal con vestidor, una sala de oficina (habitación de los niños) y un amplio baño y una terraza. En esta planta se tiene otro dormitorio con baño.\r\nEn la segunda planta se encuentra un amplio dormitorio con baño en suite y una terraza. En la llamada habitación de la torre que todavía tiene un espacio de oficina.\r\nLa casa de invitados tiene un apartamento con salón- comedor- cocina, un dormitorio y un baño y un separado dormitorio de invitados con baño.\r\nEl centro del jardín es una piscina de 20 x 6m rodeada con una gran chill-out terraza y una barbacoa cubierta. Los niños pueden jugar en el parque infantil cubierto una vela de sol o  el campo de fútbol de césped artificial.\r\nEl equipamiento interior de alta calidad incluye entre otras cosas, un sistema de calefacción por suelo radiante solar asistida en la planta baja , aire acondicionado, ventanas de doble acristalamiento de madera , estufa de cocina Corradi y nevera de Corradi, chimenea, puertas de pánico en los dormitorios principales y mucho más.\r\n5 garajes ofrecen un amplio espacio para los juguetes de papá.\r\nEsta propiedad es ideal para familias con niños y para su uso durante todo el año.\r\n\r\n'),
('90897','31303','22','precio a consultar'),
('90898','31304','22',Null),
('90899','31305','22',Null),
('90900','31306','22',Null),
('90901','31307','22',Null),
('90903','31301','5','Finca  with guest house'),
('90904','31302','5','This beautiful Finca is situated on a quiet, about 26,000 square flat plot on the outskirts  of wine-village\r\nThe idyllic finca-style villa was renovated about 7 years ago and is in top condition.\r\nThe approximately 870m ² of living space spread over 3 floors.\r\nThe ground floor is an entrance hall, guest WC, living room, TV room, dining room, 2 bedrooms each with a bathroom en suite and a country kitchen with cooking island and dining table.\r\nOn the 1st floor are the master bedroom with dressing room, an office room (children''s room)  a spacious bathroom and a terrace. On this floor there is another bedroom with bathroom.\r\nOn the 2nd floor is a large bedroom with en suite bathroom and a terrace. In the so-called tower room is an office space.\r\nThe separate guest house are an apartment with living-dining room - kitchen, a bedroom and a bathroom as well as separate guest bedroom with bathroom.\r\nThe center of the park-like garden is the 20 x 6m large swimming pool surrounded by a chill-out terrace and a covered barbecue. Children can play on the playground covered wit a sun sail or on the artificial turf football field.\r\nThe high-quality interior equipment includes, inter alia, a solar assisted under floor heating on the ground level, air conditioning, double glazed wooden windows, Corradi Kitchen stove and -fridge, fireplace , panic doors in the main bedrooms and much more.\r\n5 garages provides ample space for Dad''s toys.\r\nThis unique property is ideal for families with children and for year round use.\r\n'),
('90905','31303','5','price on request'),
('90906','31304','5',Null),
('90907','31305','5',Null),
('90908','31306','5',Null),
('90909','31307','5',Null),
('90911','31301','1','Traumfinca mit Gästehaus'),
('90912','31302','1','Diese wunderschöne Finca steht auf einem ruhig gelegenen, ca. 26.000m² flachen Grundstück, am Ortsrand eines Weindorfes\r\nDie idyllische Villa im Finca Stil wurde vor ca. 7 Jahren saniert und befindet sich in einem Top Zustand.  \r\nDie ca 870m² Wohnfläche verteilt sich auf 3 Etagen. \r\nIm EG befindet sich eine Eingangsdiele, Gäste WC, Wohnzimmer, TV Raum, Esszimmer, 2 Schlafzimmer mit je einem Bad en suite sowie eine Landhausküche mit Kochinsel und Esstisch. \r\nIm 1. OG liegen das Masterschlafzimmer mit Ankleide, ein Büroraum (Kinderschlafzimmer) sowie ein geräumiges Badezimmer und eine Terrasse. Auf dieser Etage hat es noch ein weiteres Kinderzimmer mit Badezimmer.\r\nIm 2. OG liegt ein großes Schlafzimmer mit Bad en suite und eine Terrasse. Im sogenannten Turmzimmer hat es noch einen Büroraum.\r\nIm separaten Gästehaus befinden sich ein Apartment mit Wohn-Esszimmer-Küche, ein Schlafzimmer und ein Badezimmer sowie ein separates Gäste Schlafzimmer mit Badezimmer.\r\nDer Mittelpunkt des parkähnlich angelegten Gartens ist ein 20 x 6m großer Pool mit Chill out Terrasse sowie ein überdachter Barbecue. Kinder können sich auf dem einem Sonnensegel überdachten Spielplatz oder auf dem mit Kunstrasen belegten Fußballplatz austoben. \r\nDie hochwertige Innenausstattung beinhaltet u.a. eine Solar unterstützte Fußbodenheizung im EG, Klimaanlage, Doppelglas Holzfenster, Corradi Küchenherd und-Kühlschrank, Kamin, Paniktüren in den Hauptschlafzimmern u.v.m. \r\n5 Garagen bieten ausreichend Platz für Papas Spielzeuge.\r\n'),
('90913','31303','1','Preis auf Anfrage'),
('90914','31304','1',Null),
('90915','31305','1',Null),
('90916','31306','1',Null),
('90917','31307','1',Null),
('90919','31309','1',Null),
('90920','31310','1',Null),
('90921','31311','1','1800 '),
('90922','31312','1',Null),
('90923','31313','1',Null),
('91517','31311','22','1800 '),
('91518','31311','5','1800'),
('91799','31310','5',Null),
('91800','31309','5',Null),
('91801','31312','5',Null),
('91802','31313','5',Null),
('91803','31310','22',Null),
('91804','31309','22',Null),
('91805','31312','22',Null),
('91806','31313','22',Null);
