/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('55796','19578','1','Romantisches Finca Hotel nahe Santa Maria mit herrlichem Blick auf das Tramuntana-Gebirge'),
('55797','19579','1','Das Herrenhaus aus dem Jahr 1500 wurde das letzte Mal im Jahr 1995 komplett restauriert und umgebaut, wobei die authentischen Materialien erhalten wurden.  In den letzten Jahren wurden regelmäßig kleinere Reparaturen durchgeführt sowie das Dach erneuert. \r\nDas Anwesen hat eine Wohnfläche von ca. 960 m² und steht auf einem ca. 24.100 m² großem Grundstück mit Obstbäumen und Pinienwald. Das zurzeit als Privathaus genutzte Anwesen kann man aber auch als Finca-Hotel nutzen, da es  über 10 Doppelzimmer, eine Suite und ein ca. 75 m² großes Verwalterhaus verfügt. Im Erdgeschoss befinden sich Eingang mit  Rezeption,  Speisesaal, Kaminzimmer, hochwertige Hotelküche, Wirtschaftsräumen, 3 Doppelzimmer mit je einem Badezimmer suite, überdachte Außenterrassen und Gäste-WCs. Über die großzügigen Terrassen gelangt man zum mediterran angelegten Garten mit Poolbereich (Pool 12x5,5m). Das Anwesen wird mit eigenem Brunnenwasser versorgt. Auch die auf dem Grundstück angepflanzten 650 Oliven-, Orangen- und Mandelbäume können hiermit bewässert werden. Die Hotelgäste können ihr Fahrzeug auf einem der ca. 10 Parkplätze parken. Die solarunterstützte Öl-Zentralheizung sorgt für gemütliche Wärme.\r\n400m²  des Grundstücks können noch mit einem Einfamilienhaus (ca. 240 m² Wohnfläche, 2 Etagen) bebaut werden.  Das Haupthaus und das Nebengebäude mit 2 Suiten benötigen eine komplette Sanierung um es baulich auf den heutigen Standart zu bringen. Gesamtkosten ca. 1 Mio. €.  Das Anwesen wird ohne Möbel und Dekoration, aber mit Küchenausstattung übergeben.\r\nZur Autobahn Palma –Inca sind es nur 2 Fahrminuten und zum Flughafen ca. 20 Fahrminuten.\r\n'),
('55798','19580','1',Null),
('55799','19581','1',Null),
('55800','19582','1',Null),
('55801','19583','1',Null),
('55802','19584','1',Null),
('55804','19578','5','Romantic finca hotel near Santa Maria with marvellous views of the Tramuntana mountains'),
('55805','19579','5','The manor house dating back to 1500 and 1995 was the last time completely restored and rebuilt, with the authentic materials were obtained. In recent years, minor repairs were carried out regularly and replaced the roof.\r\nThe property has an area of about 960 m² and stands on a 21,100 m² plot with fruit trees and pine forest. The currently used as a private residence property but you can use it as a country house hotel, as it has 10 double rooms and one suite. On the ground floor entrance are with reception, dining room, fireplace room, hotel quality kitchen, utility room, 3 double bedrooms with a bathroom suite, covered outdoor patios and cloakrooms. On the 1st floor there are a further 5 double bedrooms (suite) with en suite bathroom. The spacious terraces leads to the Mediterranean garden with pool area (pool 12x5,5m). The property is supplied with its own well water. The planted on the property 650 olive, orange and almond trees can hereby be irrigated. Hotel guests can park their vehicles in one of the hotel''s parking. The solar-assisted oil central heating makes for cozy warmth.\r\nThe main building and a neighboring building with 2 suites and double rooms need a complete refurbishment to bring it structurally to the present standard. Total cost about € 1 million. The property is passed without furniture and decoration, but with a professional kitchen equipment.\r\nTo Palma -Inca highway is only a 2 minute drive to the airport and about 20 minutes drive.'),
('55806','19580','5',Null),
('55807','19581','5',Null),
('55808','19582','5',Null),
('55809','19583','5',Null),
('55810','19584','5',Null),
('55812','19578','22','Romántico hotel rural cerca de Santa Maria con unas impresionantes vistas a la Sierra de Tramuntana'),
('55813','19579','22','La casa señorial que data de 1500 fue la última vez completamente restaurado y reconstruido en 1995, con la que se obtuvieron los materiales auténticos. En los últimos años, las reparaciones menores se llevaron a cabo con regularidad incluido eun techo nuevo.La propiedad tiene una superficie construida de unos 960 m² y se levanta sobre una parcela de 21.100 m² con árboles frutales y bosque de pinos. La utiliza actualmente como una propiedad residencia privada pero se puede utilizar como un hotel rural, ya que cuenta con 10 habitaciones dobles y una suite. En la entrada de la planta baja se encuentran con recepción, comedor, sala con chimenea, cocina del hotel de calidad professionel, lavadero, 3 dormitorios dobles con un baño, patios al aire libre cubiertos y vestuarios. En la primera planta hay otros 5 habitaciones dobles con baño en suite. Acerca de las amplias terrazas conduce al jardín mediterráneo con zona de la piscina (piscina 12x5,5m). La propiedad se suministra con su propio pozo de agua. El plantaron en la propiedad de 650 olivos, naranjos y almendros por este medio pueden ser regados. Los huéspedes del hotel pueden dejar su vehículo en uno de aparcamiento del hotel. La calefacción central mediante energía solar hace calor acogedor.\r\nEl edificio principal y un edificio anexo de 2 suites y habitaciones dobles necesitan una renovación completa para llevarlo estructuralmente a la presente norma. Costo total alrededor de 1 millón de €. La propiedad se pasa sin muebles y decoración, pero con un equipo de cocina profesional.\r\nPara autopista Palma -Inca está a sólo 2 minutos en coche del aeropuerto y cerca de 20 minutos en coche.'),
('55814','19580','22',Null),
('55815','19581','22',Null),
('55816','19582','22',Null),
('55817','19583','22',Null),
('55818','19584','22',Null),
('55820','19586','1','1500, renoviert 1995'),
('55821','19586','5','1500, renovated 1995'),
('55822','19586','22','1500, reformado 1995'),
('55823','19587','1',Null),
('55824','19588','1',Null),
('55825','19589','1',Null),
('55826','19590','1',Null),
('55827','19591','1',Null),
('55828','19588','5',Null),
('55829','19587','5',Null),
('55830','19589','5',Null),
('55831','19590','5',Null),
('55832','19591','5',Null),
('55833','19588','22',Null),
('55834','19587','22',Null),
('55835','19589','22',Null),
('55836','19590','22',Null),
('55837','19591','22',Null);
