/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('96056','33139','1','Finca mit 3 Häusern in Mallorca zu verkaufen'),
('96057','33140','1','Diese Finca mit 3 Gebäuden steht auf einem ca 75.000m² großen, flachen Grundstück, inmitten einer Naturschutzzone. Zum Meer sind es nur 15km.\r\nHaus I bietet Platz für 8 Pers.Es hat ca 350m² Wohnfläche die sich aufteilen in 4 SZ (3 twins,1 doppelt), 3 Badezimmer, zusätzl 1 WC, Wohnzimmer mit Kamin, Küche, Essplatz und ein Billardraum. Im Außenbereich hat es noch Terrassen, eine Sportecke mit Basketball, Tischtennis, Pool ect.\r\nHaus II bietet Platz für 4-6 Pers. Das Loftartige Haus hat ca 60m² Wohnfläche mit 2 SZ, 2 Badezimmer en suite, Küche, Wohn-Eßzimmer, ein separates SZ mit Badezimmer en suite. Auch hier hat es eine schöne Terrasse zum Relaxen und einen Pool.\r\nHaus III hat eine separate Zufahrt und wird zurzeit vom Eigentümer der Finca bewohnt, kann aber auch vermietet werden. Es hat ca 380m² Wohnfläche und die sich auf 4 SZ, 3 Badezimmer, Wohn-Esszimmer, WC und Küche verteilen. Ein angelegter Garten und ein Pool schließen das Angebot ab. Vermietungslizenzen liegen vor. Ein heller ca 80m² klimatisierter Raum mit Parkettboden und großem Wandspiegel eignet sich als Multifunktionsraum oder Jogaraum. Das Anwesen liegt in einer absolut ruhigen Lage\r\n'),
('96058','33141','1',Null),
('96059','33142','1',Null),
('96060','33143','1',Null),
('96061','33144','1',Null),
('96062','33145','1',Null),
('96064','33139','5','Finca with 3 houses in Mallorca for sale'),
('96065','33140','5','This country house with 3 buildings is situated on a 75,000 m² ca large flat plot, surrounded by a nature conservation zone. The sea is only 15km away.\r\nHouse1 can accommodate 8 Pers. It has about 350m² of living space which are divided into 4 bedrooms (3 twins, 1 double), 3 bathrooms, 1 restroom, living room with fireplace, kitchen, dining area and a billiard room. Outside, there has terraces, a sports area with a basketball, table tennis, pool.\r\nHouse 2 can accommodate 4-6 persons. The Loft-like home has about 60m² of living space with 2 bedrooms, 2 bathrooms en suite, kitchen, living-dining room, a separate bedroom with bathroom en suite. Again, it has a beautiful terrace to relax and a pool.\r\nHouse 3 currently has a separate entrance and is inhabited by the owner of the finca, but can also be rented. It has approximately 380m² of living space and spread over 4 bedrooms, 3 bathrooms, living-dining room, toilet and kitchen. A landscaped garden and a swimming pool complete the offer. Rental licenses are available. A bright ca 80m² air-conditioned room with parquet floors and large wall mirror can be used as multi-purpose room or Joga room. The property is located in an absolutely quiet location.\r\n'),
('96066','33141','5',Null),
('96067','33142','5',Null),
('96068','33143','5',Null),
('96069','33144','5',Null),
('96070','33145','5',Null),
('96072','33139','22','Finca vacacional con 3 casas en Mallorca en venta'),
('96073','33140','22','Esta Finca vacacional con 3 edificios se encuentra en una gran parcela plana de 75.000 m² ca, rodeado de una zona de conservación de la naturaleza. El mar está a sólo 15 km.\r\nHouse I tiene capacidad para 8 Pers. Los 350m² habitable se dividen en 4 dormitorios (3 dobles, 1 doble), 3 baños, 1 aseo, salón adicional con chimenea, cocina, comedor y una sala de billard. Afuera, tiene terrazas, ect una zona deportiva con un baloncesto, tenis de mesa ect.\r\nCasa 2 tiene capacidad para 4-6 personas. La casa estilo Loft, tiene aprox. 60m² habitable con 2 dormitorios, 2 baños en suite, cocina, salón-comedor, un dormitorio con baño en suite. Una vez más, tiene una hermosa terraza para relajarse y una piscina.\r\nCasa 3 actualmente tiene una entrada independiente y está habitada por el propietario de la finca, pero también se pueden alquilar. Tiene aproximadamente 380m² de espacio habitable, tiene 4 dormitorios, 3 baños, salón-comedor, aseo y cocina. Un jardín y una piscina completan la oferta. Licencias de alquiler estan actualisada. Un 80m² ca luminosa sala con aire acondicionado, suelos de parqué y un gran espejo de pared se puede utilizar como sala de usos múltiples o para claes de yogar. La propiedad está situada en una zona muy tranquila\r\n'),
('96074','33141','22',Null),
('96075','33142','22',Null),
('96076','33143','22',Null),
('96077','33144','22',Null),
('96078','33145','22',Null),
('96080','33147','1',Null),
('96081','33148','1',Null),
('96082','33148','5',Null),
('96083','33147','5',Null),
('96084','33148','22',Null),
('96085','33147','22',Null);
