/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('69840','24262','1','Ultimative Neubau Villa in der Gemeinde Calvia'),
('69841','24263','1','Eine der spektakulärsten Null-Energie-Villen, die zurzeit auf Mallorca angeboten wird! Sie steht auf einem knapp 2.000 m² großen Grundstück, das an ein unverbaubares Naturschutzgebiet angrenzt. Ein ca. 100 m langer Fußpfad führt zu einer kleinen, idyllischen Badebucht.\r\nDer zweigeschossige, terrassierte, moderne und Licht durchflutete Baukörper passt sich der Topografie des Grundstückes an und setzt sich im Außenwohnbereich mit Sommerküche Poollandschaft, Whirlpool mit Wasserfall und Lichtspielen fort. \r\nDie ca. 840 m² konstruierte Fläche verteilt sich auf 2 Wohnebenen. Das optische Highlight des Wohnraumes bildet ein allseitig verglastes Atrium mit Wasserbecken, Lichtspielen und Bepflanzung. Die Villa bietet 5 Schlafzimmer mit Badezimmern en suite, 2 Gäste-WCs, moderne Küche, Esszimmer, Wohnzimmer, Kaminzimmer, Spabereich mit Dampfsauna sowie einen rollstuhlgängigen Lift und eine Doppelgarage. Die meisten Bereiche der Villa sind barrierefrei zu erreichen.\r\nEin renommiertes, international tätiges, deutsches Ingenieurbüro hat die geometrisch komplexen Stahlbetonkonstruktionen aus Stützen, Wandscheiben und Flachdecken geplant. Hohe Glasfassaden, Edelstahl und helle Quarzfußböden wurden mit größter Sorgfalt und Präzision verarbeitet. \r\nHier eine kleine Auswahl an technischen Details: Sonnenkollektoren und Photovoltaik, Kühlung über Decken, Fußbodenheizung, geräuschloses Luftreinigungs- und Befeuchtungssystem, professionelle Dachabdichtung realisiert von international tätiger Fachfirma, elektrische (fern-) bedienbare Glasschiebetüren (SCHÜKO), dreifach verglaste Fenster mit innenliegenden elektrischen Jalousien, LED Beleuchtung in blau und weiß, Alarmsystem, Kameraüberwachung und vieles mehr. Bedient wird die gesamte Elektrik dieser energieautarken Villa über ein BUS System, auch über PC von außerhalb steuerbar. Diese Villa sucht einen technikinteressierten Käufer, der die Annehmlichkeiten der heutigen Technik im Zusammenspiel mit hochwertigen Materialien zu schätzen weiß.\r\nHat dieses Objekt Ihr Interesse geweckt und Sie möchten weitere Informationen? Dann teilen Sie uns bitte Ihre Postanschrift und eine Festnetznummer mit, damit wir Sie kontaktieren können.'),
('69842','24264','1','auf Anfrage'),
('69843','24265','1',Null),
('69844','24266','1',Null),
('69845','24267','1',Null),
('69846','24268','1',Null),
('69848','24262','5','The ultimate villa, located in the municipality of Calvia'),
('69849','24263','5','This is one of the most spectacular zero energy houses in Mallorca! It stands on a plot of approx. 2,000 m² adjacent to an unobstructable nature protection area. A small footpath leads to an idyllic, hidden beach.\r\nThe terraced, light-flooded house in modern style adapts in an intelligent manner the situation of the plot maximizing the use of the sun. Also the outdoor area fits perfectly to the overall concept and comprises of a summer kitchen, seating area, swimming pool and whirlpool with waterfall and illumination effects.\r\nThe constructed area of approx. 840 m² spreads over 2 levels. A glazed atrium with pond and beautiful illumination surrounded by plants forms the visual centrepiece of the house. The villa offers 5 bedrooms with en suite bathrooms, a modern kitchen, dining room, living room with fireplace, 2 guest toilets, a spa area with steam room, a disabled friendly lift and a double garage. Most of the areas of the villa are handicapped accessible.\r\nA renowned, internationally operating, German engineering company planned the geometrically complex reinforced concrete structure consisting of columns, shear walls and flat slabs. Large glass facades, stainless steel and bright quartz floors were processed with the utmost care and precision.\r\nHere is a small selection of technical details: solar panels and photovoltaic, cooling ceilings, under floor heating, noiseless air cleaning and air moistening system, the waterproofing of the roofs was realized by an internationally active specialist, electrically (remote-) controlled sliding glass doors (SCHÜKO), triple-glazed windows with internal electric blinds, LED blue and white lighting, alarm system, video surveillance and many more. The entire electrical system of this zero energy villa is controlled by BUS home automation system which is accessible also from an external PC. This villa is made for technophiles who appreciate the convenience of latest technical standards in conjunction with first class materials.\r\nIf you would like to have more information about this property, please send us an email with your postal address and landline number and we will contact you immediately.'),
('69850','24264','5','on application'),
('69851','24265','5',Null),
('69852','24266','5',Null),
('69853','24267','5',Null),
('69854','24268','5',Null),
('69856','24262','22','Única villa de nueva construcción en el municipio de Calvià'),
('69857','24263','22','Una de las casas más espectaculares de energía cero, que están en venta en Mallorca! Se sitúa en un terreno con pendiente de 2.000 m², adyacente a una protegida zona verde. Un caminito de 100 metros conduce a una pequeña e idílica cala.\r\nEl luminoso edificio de estilo moderno se adapta perfectamente a la topografía del terreno, así como la zona exterior con piscina, cocina del verano y jacuzzi con cascada e iluminación.\r\nLa superficie construida es de aprox. 840 m² y se distribuye en 2 plantas. Lo que atrae todas las miradas al entrar a la casa es, sin duda, el precioso atrio de cristal que tiene una balsa iluminada rodeada de plantas. La villa dispone de 5 dormitorios, todos con baños en suite, 2 aseos, moderna cocina, comedor, salón con chimenea, una zona de spa con baño de vapor, un ascensor apto para minusválidos y un garaje doble. La mayoría de las áreas de la villa son accesibles sin barreras.\r\nUna prestigiosa empresa internacional de ingeniería situada en Alemania ha planeado las geométricas estructuras de la construcción de hormigón armado que se compone de soportes, discos de pared y techo plano. Altas fachadas de vidrio, acero inoxidable y suelos de cuarzo fueron procesados con un máximo de esmero y precisión.\r\nLas instalaciones son de la última tecnología e inlcuyen: placas solares fotovoltaicas y térmicas, refrigeración a través del techo, calefacción por suelo radiante, sistema silencioso de filtraje y humidificación del aire, impermebilización de la azotea por una empresa especializada, puertas correderas de cristal accionadas electronicamente (también por mando a distancia) de la marca SCHÜKO, ventanas con triple acristalamiento y persianas eléctricas en el interior, iluminación por LEDs en azul y blanco, alarma centralizada, videovigilancia y mucho más. El equipo eléctrico de esta autosuficiente casa se controla completamente a través de un sistema domótico de BUS que también está manejable desde el exterior. Esta villa es lo último para interesados en la técnica que saben apreciar las comodidades de la moderna tecnología en conjunción con las mejores calidades en construcción.\r\nÚsted está interesado y quiere más información? No dude en contactarnos indicando su dirección postal y un número de teléfono fijo y nos pondrémos en contacto con usted inmediatamente.'),
('69858','24264','22','a consultar'),
('69859','24265','22',Null),
('69860','24266','22',Null),
('69861','24267','22',Null),
('69862','24268','22',Null),
('69864','24270','1','2012'),
('69865','24270','5','2012'),
('69866','24270','22','2012'),
('69867','24271','1',Null),
('69868','24272','1',Null),
('69869','24273','1',Null),
('69870','24274','1',Null),
('69871','24275','1',Null),
('69872','24272','5',Null),
('69873','24271','5',Null),
('69874','24273','5',Null),
('69875','24274','5',Null),
('69876','24275','5',Null),
('69877','24272','22',Null),
('69878','24271','22',Null),
('69879','24273','22',Null),
('69880','24274','22',Null),
('69881','24275','22',Null);
