/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('98298','33919','1','Neu renovierte Villa in Paguera zu verkaufen'),
('98299','33920','1','Diese sehr schöne neu renovierte Villa steht am Ortsrand von Paguera nur wenige Gehminuten vom schönen Sandstrand entfernt. \r\nDiese exklusive Villa von ca. 800m2 Wohnfläche besticht durch das gekonnte Design. Empfangen wird man durch ein grosszügiges Entree, das Erdgeschoss teilt sich in Wohnzimmer von dem man einen herrlichen Blick auf Garten und Pool bekommt, sowie Gästezimmer mit WC/Bad ensuite, ebenso befindet sich die sehr praktische neue Bulthaupt Küche mit allem was man sich in einer modernen Kusche wünscht im  Erdgeschoss. Im Obergeschoss, das man bequem mit dem Aufzug erreichen kann, befinden sich 5 grosszügige Schlafzimmer 2 davon mit Bad/WC ensuite.\r\n\r\nDer Aussenbereich befinden sich schöne Terassen eine Aussenküche sowie ein schön angelegter Pool an dem man die Ruhe geniessen kann.\r\n\r\nEine Tiefgarage für 6 Autos sowie diverse Abstellräume bieten genug Platz für alles.\r\n'),
('98300','33921','1',Null),
('98301','33922','1',Null),
('98302','33923','1',Null),
('98303','33924','1',Null),
('98304','33925','1',Null),
('98306','33919','5','Newly renovated villa in Paguera for sale'),
('98307','33920','5','This beautiful newly renovated villa is a short walk from the beautiful sandy beach on the outskirts of Paguera.\r\nThis exclusive villa of about 800m2 living space offers the skillful design. Receiving one is a generous entrance, the ground floor is divided into living room from where you get a magnificent view of the garden and pool, as well as en-suite guest rooms with WC / bathroom, as is the very practical new Bulthaupt kitchen with everything you could in itself a modern Kusche wishes on the ground floor. Upstairs, the can easily be reached by a lift, located 5 spacious bedrooms 2 of them with bathroom / WC are ensuite.\r\n\r\nThe outdoor area is home to beautiful terraces an outdoor kitchen and a beautifully landscaped swimming pool where you can enjoy the tranquility.\r\n'),
('98308','33921','5',Null),
('98309','33922','5',Null),
('98310','33923','5',Null),
('98311','33924','5',Null),
('98312','33925','5',Null),
('98314','33919','22','Villa de nueva renovado en Paguera a la venta'),
('98315','33920','22','Esta hermosa villa recientemente reformada, está a pocos pasos de la hermosa playa de arena en las afueras de Paguera.\r\nEsta exclusiva villa de unos 800m2 espacios de vida ofrece el diseño hábil. Recibiendo una es una entrada generosa, la planta baja se divide en salón desde donde se obtiene una magnífica vista del jardín y la piscina, así como habitaciones con baño privado, WC / baño, al igual que la muy práctica nueva cocina Bulthaupt con todo lo que en sí mismo un Kusche moderna desea en la planta baja. Arriba, el fácilmente se puede llegar en ascensor, situado a 5 amplios dormitorios 2 de ellos con baño / WC son en suite.\r\n\r\nLa zona al aire libre es el hogar de hermosas terrazas una cocina al aire libre y una piscina bellamente ajardinado donde se puede disfrutar de la tranquilidad.\r\n\r\nUn aparcamiento subterráneo para 6 coches y varios trasteros ofrecen suficiente espacio para todo.\r\n'),
('98316','33921','22',Null),
('98317','33922','22',Null),
('98318','33923','22',Null),
('98319','33924','22',Null),
('98320','33925','22',Null),
('98322','33927','1',Null),
('98323','33928','1',Null),
('98324','33929','1',Null),
('98325','33930','1',Null);
