/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('95904','33083','22','7 apartamentos en venta con piscina en la costa este de Mallorca'),
('95905','33084','22','Sólo 500 metros de distancia de la playa y un puerto de la ciudad idílica, es este complejo apartamentos vacacional de estilo finca. Los apartamentos tiene una licencia VTV (Viviendas Turísticas-Vacacionales-). Hay 7 apartamentos disponibles, divididos de la siguiente manera: 4 Bungalows de 49m², con una habitación doble y dos sofás-cama en la sala de estar, cocina, sala, comedor, cuarto de baño con ducha, terraza con vistas a la piscina / jardín.   1 Torre Apartamento, 79 m², primera planta con dos dormitorios dobles, cocina, sala de estar, baño con ducha, terraza con vistas a la piscina / jardín. 1 Apartamento Torre, 79 metros cuadrados, primera planta con dos dormitorios dobles, cocina, sala de estar, dos baños con ducha, balcón (unos 40 m²) a la piscina / jardín. un adosado esquina, alrededor de 119 metros cuadrados, 2 plantas, con tres habitaciones dobles (con aire acondicionado), cocina, sala, comedor, dos baños con ducha, balcones y terrazas a la piscina / jardín. En el exterior hay una amplia zona de piscina para los huéspedes. Confiable-guardado!'),
('95906','33085','22',Null),
('95907','33086','22',Null),
('95908','33087','22',Null),
('95909','33088','22',Null),
('95910','33089','22',Null),
('95912','33083','5','7 holiday apartments with pool on the east coast of Majorca for sale'),
('95913','33084','5','Only 500m from the beach and an idyllic harbor town away, is this well-maintained holiday apartment complex in finca style. The apartments are operated with a license VTV (Viviendas Turisticas-Vacacionales). There are 7 apartments available, divided as follows:4 Bungalows, each 49 sqm, with a double room and two sofa beds in the living room, kitchen, living room, bathroom with shower, terrace overlooking the pool / garden. 1 Tower Apartment, 79 sqm, first floor with two double bedrooms, kitchen, living room, bathroom with shower, terrace overlooking the pool / garden. 1 Tower apartment, 79 square meters, 1st floor with two double bedrooms, kitchen, living room, two bathrooms with shower, balcony (about 40 sqm) to the pool / garden. Attached house, about 119 sqm, 2 floors with three double bedrooms (air conditioned), kitchen, living room, two bathrooms with shower, balconies and terraces to the pool / garden. Outside there is a spacious pool area for guests. All in exelent condition!'),
('95914','33085','5',Null),
('95915','33086','5',Null),
('95916','33087','5',Null),
('95917','33088','5',Null),
('95918','33089','5',Null),
('95920','33083','1','7 Ferienapartments mit Pool an der Ostküste Mallorcas zu verkaufen'),
('95921','33084','1','Nur 500m vom Strand und einem idyllischen Hafenstädtchen entfernt, steht diese sehr gepflegte Ferien. Apartmentanlage in Finca Stil. Die Anlage wird mit einer VTV Lizenz (Viviendas-Turisticas-Vacacionales)  betrieben. Es stehen 7 Apartments zur Verfügung, die sich wie folgt aufteilen:  4 Reihenbungalows ,a 49 qm,  mit einem Doppelzimmer und zwei Schlafcouches im Wohnraum, Küche, Wohnraum, Bad mit Dusche, Terrasse zum Pool/Garten.    Turmappartement, 79 qm, Erdgeschoss mit zwei Doppelzimmern, Küche, Wohnraum, Bad mit Dusche, Terrasse zum Pool/Garten.    Turmappartement, 79 qm, 1. Etage mit zwei Doppelzimmern, Küche, Wohnraum, zwei Bäder mit Dusche, Balkon (ca. 40 qm) zum Pool/Garten.    Reiheneckhaus, ca. 119 qm, doppelgeschossig mit drei Doppelzimmern (klimatisiert), Küche, Wohnzimmer, zwei Bäder mit Dusche, Balkone und Terrassen zum Pool/Garten.  Im Außenbereich hat es einen großzügig angelegten Poolbereich für die Gäste. Top gepflegte Anlage!\r\n\r\n'),
('95922','33085','1','Preis auf Anfrage'),
('95923','33086','1',Null),
('95924','33087','1',Null),
('95925','33088','1',Null),
('95926','33089','1',Null),
('95928','33091','22','1790'),
('95929','33091','5','1790'),
('95930','33091','1','1790'),
('95931','33092','1',Null),
('95932','33093','1',Null),
('95933','33094','1',Null),
('95934','33095','1',Null);
