/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('95840','33059','1','Ferienfinca auf Mallorca mit 3 Häusern zu verkaufen'),
('95841','33060','1','Die Finca befindet sich in einer ruhigen uneinsehbarer Alleinlage im Süden von Mallorca auf einem ca 22.000² großen Grundstück und nur 5 km vom bekannten Naturbadestrand Es Trenc entfernt. Die umliegenden Orte wie Campos, Sa Rapita, Colonia Sant Jordi und Santanyi sind in wenigen Autominuten zu erreichen, dort finden sie Einkaufsmöglichkeiten, Restaurants, Schulen, Ärzte und Apotheken. Bis zum Flughafen sind es ca. 35 Autominuten. \r\nZur Verfügung stehen je zwei 75 m² große Doppelhaushälften mit jeweils zwei Doppelschlafzimmern, Wohn – Essbereich, komplett ausgestattete Küche, Bad, Sat TV, Internet und Terrasse. Sowie ein 160 m² große Haupthaus mit zwei Doppelschlafzimmern, zwei Bäder, komplett ausgestattete Küche, Kaminzimmer, Wohnzimmer, Essbereich, Sat TV, Internet und großer überdachter Terrasse. Zur Ausstattung gehören alle Möbel, Ölzentral/ Fußbodenheizung im Doppelhaus, Fußboden – und Radiatorenheizung im Haupthaus, Klimaanlage w/k, Strom-Wasser- und Tel Anschluss, Internet- WIFI, Tiefbrunnen mit Wasser für Landwirtschaft, sowie ein Traktor und Landwirtschaftliche Geräte. \r\nAuf dem Grundstück wird Oliven – und Weinanbau betrieben. Alle Olivenbäume (ca  350 Stck. mit ca 600l Öl / Jahr) und ca 1000 Weinstöcke  (u.a. Chardonay), werden mit Wasser aus dem eigenen Tiefbrunnen automatisch'),
('95842','33061','1',Null),
('95843','33062','1',Null),
('95844','33063','1',Null),
('95845','33064','1',Null),
('95846','33065','1',Null),
('95848','33059','5','Finca with 3 houses and holyday rental licenc for sale'),
('95849','33060','5','The house is situated in a quiet secluded secluded location in the south of Mallorca on a ca 22.000² of grounds and just 5 km from the famous natural beach Es Trenc. The surrounding towns like Campos, Sa Rapita, Colonia Sant Jordi and Santanyi can be reached in a few minutes, where you will find shops, restaurants, schools, doctors and pharmacies. The airport is about 35 minutes by car.\r\nAt your disposal are two 75 per square meter semi-detached houses with two double bedrooms, living - dining area, fully equipped kitchen,  bathroom, satellite TV and Internet and terrace. And a 160 m² large main house with two double bedrooms, two bathrooms, fully equipped kitchen, fireplace, living room, dining area, satellite TV, Internet and a large covered terrace. Facilities include all the furniture, oil central / floor heating in detached house, floor - and radiator heating in the main house, air conditioning h / c, electricity-water and phone connection, Internet WIFI, deep wells with water for agriculture, and a tractor and agricultural equipment.\r\nOn the property are approx 350 cultivated olive trees - and 1000 vines. All olive trees (yearly product approximately 600l) and vines (about 1000 vines, including Chardonnay) are automatically irrigated with water from their own deep wells. Furthermore impressed the estate with the beautiful mediterrane Cactus garden, Palmtrees, swimming pool - and covered spa with sauna, outdoor shower, hot tub and relaxation area by the pool\r\n'),
('95850','33061','5',Null),
('95851','33062','5',Null),
('95852','33063','5',Null),
('95853','33064','5',Null),
('95854','33065','5',Null),
('95856','33059','22','Casa Finca en Mallorca en venta con 3 casas'),
('95857','33060','22',' La casa está situada en un lugar aislado tranquila, aislada en el sur de Mallorca en un ca 22.000² terreno y sólo 5 km de la famosa playa natural de Es Trenc. Los pueblos de los alrededores, como Campos, Sa Rapita, Colonia Sant Jordi y Santanyí se puede llegar en pocos minutos, donde encontrará tiendas, restaurantes, escuelas, médicos y farmacias. El aeropuerto está a unos 35 minutos en coche.\r\nA su disposición son dos 75 casas adosadas metros cuadrados con dos dormitorios dobles, salón - comedor, cocina totalmente equipada, cuarto de baño, televisión por satélite e Internet y terraza. La casa principal tiene 160m² con dos habitaciones dobles, dos baños, cocina totalmente equipada, chimenea, sala de estar, comedor, TV vía satélite, Internet y una gran terraza cubierta. Las instalaciones incluyen todos los muebles, central de gasoil / calefacción por suelo radiante en las 2 viviendas unifamiliar, planta - y calefacción por suelo y radiadores en la casa principal, aire acondicionado f / c, agua electricidad y teléfono de conexión, Internet WIFI, pozos profundos con agua para la agricultura, y un tractor y equipo agrícola.\r\nEn la propiedad se produce aceite de oliva - y vino. Todos los arboles olivos (aprox 350 uds. con aproximadamente 600l de aceite al ano) y vides (alrededor de 1000, incluyendo Chardonnay) se riegan de forma automática con el agua de sus propios pozos profundos. Además impresionado la finca con la hermosa mediterraneojardin de cactus, palmeras,  piscina - y cubierta de spa con sauna, ducha al aire libre, bañera de hidromasaje y zona de relax en la piscina\r\n'),
('95858','33061','22',Null),
('95859','33062','22',Null),
('95860','33063','22',Null),
('95861','33064','22',Null),
('95862','33065','22',Null),
('95864','33067','1',Null),
('95865','33068','1',Null),
('95866','33069','1',Null),
('95867','33070','1',Null);
