/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('94462','32541','1','Villa im eleganten Finca Stil Nähe Manacor zu verkaufen'),
('94463','32542','1','Diese schicke und sehr gepflegte Villa, im eleganten Finca Stil, steht auf einem ca 16.000m2 großen Grundstück mit Panoramablick. Manacor und mehrere Golfplätze liegen in unmittelbarer Umgebung. Das Haus mit ca 350m² Wohnfläche bietet auf der Hauptwohnebene ein Wohn-Esszimmer, offene Landhausküche mit Hauswirtschaftsraum, Gäste Schlafzimmer, Gäste WC & Dusche, großen Büroraum mit Zugang zum Garten, sowie Hauptschlafzimmer mit geräumigem Badezimmer en suite. Vom Wohnzimmer und der Küche aus hat man Zugang zu einer teilweisen überdachten chilligen Terrasse.\r\nIm Untergeschoß befinden sich ein Gästeapartment und ein Saunabereich mit Zugang zum Garten sowie Technikräume und ein Kellerraum. Das Gäste-Apartment besteht aus einem kleinen Wohnzimmer mit Küchenzeile, 2 Schlafzimmer, ein Badezimmer und ein WC. Des Weiteren bietet die Villa auf dieser Ebene noch ein separates Gäste Schlafzimmer mit Küchenzeile und Badezimmer. Der mediterrane angelegte Garten wird mit Wasser aus dem eigenen Brunnen automatisch bewässert. Fotovoltaik unterstützt die Stromversorgung. Eine Gaszentralheizung sorgt auch an kühleren Tagen für die richtige Temperatur. Ein Aussenpool mit Terrasse, inmitten des wunderschön angelegten und pflegeleichten Gartens, rundet das Angebot ab.\r\n\r\n'),
('94464','32543','1',Null),
('94465','32544','1',Null),
('94466','32545','1',Null),
('94467','32546','1',Null),
('94468','32547','1',Null),
('94470','32541','5','Country house in elegant style near Manacor for sale'),
('94471','32542','5','This chic and very well maintained villa, in the elegant country house style, stands on a ca 16.000m² of land with panoramic views. The city Manacor and several golf courses are nearby. The house has approx 350m² of living space. On the main level are, a living-dining room, open country kitchen with utility room, guest bedroom, guest toilette & shower, large office space with access to the garden, and master bedroom with spacious bathroom en suite. From the living room and the kitchen you have access to a partly covered terrace chill.\r\nIn the basement is a guest apartment and a sauna area with access to the garden aswella technik room and a cellar. The guest apartment consists of a small living room with kitchenette, 2 bedrooms, a bathroom and a toilet. Furthermore there is a separate guest bedroom with kitchinette and bathroom. The Mediterranean landscaped garden is automatically irrigated with water from their own wells. The house is powered via the main red and photovoltaic power. Gas central heating ensures even on cooler days for the right temperature. An outdoor swimming pool with terrace, in the midst of beautifully landscaped and easy to maintain garden completes the offer.\r\n'),
('94472','32543','5',Null),
('94473','32544','5',Null),
('94474','32545','5',Null),
('94475','32546','5',Null),
('94476','32547','5',Null),
('94478','32541','22','Villa elegante de estilo „Finca“ cerca de Manacor para vender'),
('94479','32542','22','Esta villa, muy bien mantenido, se encuentra en un solar de 16.000m² con vistas panorámicas. Manacor y varios campos de golf están cerca. La casa con unos 350m² de espacio habitable, hay en la planta principal, una sala de estar-comedor, cocina abierta, lavadero, dormitorio de invitados, aseo y ducha, gran espacio de oficina con acceso al jardín, y el dormitorio principal con amplio baño en suite. Desde el salón y la cocina se accede a una terraza parcialmente cubierta.\r\nEn el sótano hay un apartamento de invitados y una zona de sauna con acceso al jardín, un sala tecnica y un trastero. El apartamento de invitados se compone de una pequeña sala de estar con cocina, 2 dormitorios, un baño y un aseo. Ademas hay un dormitorio de invitados, cocina americana y baño. El jardín mediterráneo se riega automáticamente con agua de sus propios pozos. La casa se alimenta a través de la red eléctrica y de energía fotovoltaica. Calefacción central de gas asegura los días más fríos de la temperatura adecuada. Hay una piscina exterior con terraza, en medio de hermoso paisaje\r\n'),
('94480','32543','22',Null),
('94481','32544','22',Null),
('94482','32545','22',Null),
('94483','32546','22',Null),
('94484','32547','22',Null),
('94486','32549','22','2004'),
('94487','32549','5','2004'),
('94488','32549','1','2004'),
('94489','32550','1',Null),
('94490','32551','1',Null),
('94491','32552','1',Null),
('94492','32553','1',Null),
('94493','32551','5',Null),
('94494','32550','5',Null),
('94495','32552','5',Null),
('94496','32553','5',Null),
('94497','32551','22',Null),
('94498','32550','22',Null),
('94499','32552','22',Null),
('94500','32553','22',Null);
