/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('54024','19104','1','Gemütliches Landhotel zu verkaufen'),
('54025','19105','1','Das herrschaftliche Landgut aus dem 16. Jahrhundert ist umgeben von einem mediterranem Garten, einer reichen Vielzahl von Mandel-, Orangen-, Zitronen- und Feigenbäumen sowie von Getreidefeldern. Eingebettet in eine romantische Hügellandschaft liegt es nur 7 Autominuten entfernt zum Meer mit seinen herrlichen Badebuchten.\r\nIm Juli 1999 (nach aufwändiger Restaurierung) wurde daraus ein stilvolles Landhotel, das höchsten Ansprüchen genügt. Das mit Kunst und Antiquitäten liebevoll eingerichtete Hotel vermittelt Behaglichkeit und wunderschönes, authentisches Ambiente. Eine Oase zum Wohlfühlen und um die „Seele“ baumeln zu lassen.\r\nIn 15 – 25 Autominuten sind 5 Golfplätze zu erreichen und nur 5 Autominuten entfernt soll ein weiterer Golfplatz entstehen.\r\nDas Anwesen mit 57.000 m² großem Grundstück und 1.600 m² Wohn-Nutzfläche hat einen eigenen Wasserbrunnen und ein Wasserdepot. Strom- und Telefonanschlüsse sind vorhanden.\r\nEs gibt 9 Doppelzimmer, 2 Junior Suiten (eine mit Dachterrasse), 3 Suiten (eine mit Dachterrasse), 1 Apartment (54m² mit kl. Küche), die alle ausgestattet sind mit Bad en suite, ISDN Telefonleitung für Internet, Sat-TV Anschluss, Minibar, Safe, Klimaanlage w/k u.v.m.\r\nDie Erweiterung um 2 weitere Doppelzimmer ist einfach. Außerdem ist die Möglichkeit gegeben weitere 3 Doppelzimmer zu schaffen durch den Umbau einer Ruine. Zum Hotel gehören Rezeption, Empfangshalle, Kaminzimmer, Bar, Salon, Bibliothek, Restaurant mit Profiküche, diverse Abstellräume und begehbare Kühl/Gefrierräume sowie ein Fitnessraum mit Massagebereich und Sauna mit Solarium.\r\nEine großzügig gepflegte parkähnliche Gartenanlage mit automatischer Bewässerung, eine umfangreiche Außenbeleuchtung, ein Pferdestall mit 6 Boxen inkl. Wasser und Licht, ein großer Pool und  ein Tennisplatz runden das Paket ab.\r\nDa sich das Hotel noch im laufenden Betrieb befindet können wir aus Gründen der Diskretion keine Fotos und direkten Ortsangaben veröffentlichen. Bei Interesse setzten Sie sich bitte mit unserem Büro in Verbindung. '),
('54026','19106','1','auf Anfrage'),
('54027','19107','1',Null),
('54028','19108','1',Null),
('54029','19109','1',Null),
('54030','19110','1',Null),
('54032','19104','5','Comfortable country hotel for sale'),
('54033','19105','5','This stately manor dated from the 16th century is surrounded by a Mediterranean garden, a rich variety of almond, orange, lemon and fig trees and ample fields of grain. Nestled in romantic hills, it is only a 7 minutes drive away from the sea with its beautiful beaches.\r\nIn July 1999 (after extensive restoration) it was converted into an elegant country hotel, that satisfies the highest demands. It is decorated with tastefully selected artwork and antiques, which provide comfort and a beautiful, authentic atmosphere. A perfect place for letting go and unwinding.\r\nFive different golf courses will be reached within 15-25 minutes by car, and another golf course will be built just a 5 minutes drive away.\r\nThe property is set on plot of 57,000 m² with a living area of 1,600 m² and has an own water supply well plus a water deposit. Electricity and telephone connections are installed.\r\nThere are 9 double rooms, 2 junior suites (one with roof terrace), 3 suites (one with roof terrace), 1 apartment (54 m² including a kitchenette), all equipped with en suite bathroom, ISDN telephone line for internet, satellite TV connection, minibar, safe, air conditioning h / c, etc.\r\nThe extension of two further double room is easy. Moreover, there is the possibility to create 3 double rooms by reconstructing a ruin. The hotel has reception, lobby, fireplace, bar, lounge, library, restaurant with professional kitchen, various storage rooms and walk-in refrigerator / freezing rooms and a fitness room with massage area and sauna with solarium.\r\nA large, well-maintained park-like garden with automatic irrigation, wide outdoor lighting, a horse stable with 6 boxes/stalls including water and light, a large pool and a tennis court complete this offer.\r\nAs the hotel is still in operation and for discretionary purposes, we are not able to publish any photos and location details. Please contact our office for further information.'),
('54034','19106','5','on application'),
('54035','19107','5',Null),
('54036','19108','5',Null),
('54037','19109','5',Null),
('54038','19110','5',Null),
('54040','19104','22','Confortable hotel rural en venta'),
('54041','19105','22','Esta mansión señorial del siglo XVI. está rodeada por un jardín mediterráneo, una gran variedad de almendros, naranjos, limoneros, higueras y amplias campos de cereales. Enmarcado en un romántico paisaje con colinas, está a sólo 7 minutos del mar con sus bonitas calas.\r\nEn julio del año 1999 (después de una profunda reformación) se convertió en un elegante hotel rural, que colma las exigencias más altas. El hotel está decorado con obras de arte y antigüedades cuidadosamente seleccionadas, que crean un agradable y auténtico ambiente. Aquí se encuentra un lugar perfecto para relajarse y dejar volar el alma.\r\nSe llega a 5 diferentes campos de golf en 15-25 minutos en coche, y actualmente se construyen otro campo de golf que está a tan sólo 5 minutos.\r\nLa propiedad con una superficie habitable de 1.600 m² se situa en un terreno de 57.000 m² y tiene un pozo propio más un depósito de agua. Las conexiones de electricidad y del teléfono están instaladas.\r\nHay 9 habitaciones dobles, 2 junior suites (uno de ellos con azotea), 3 suites (uno de ellos con azotea), 1 apartamento (de 54 m² con pequeña cocina). Todas las habitaciones están equipadas con cuarto de baño, línea telefónica RDSI para internet, conexión de TV por satélite, minibar, caja fuerte, aire acondicionado f / c, etc.\r\nSe puede ampliar el hotel con dos habitaciones dobles mas. Además, existe la posibilidad de reconstruir una ruina y crear 3 adicionales habitaciones dobles. El hotel cuenta con recepción, vestíbulo, cuarto de chiminea, bar, salón, biblioteca, restaurante con cocina profesional, varios trasteros y cámaras frigoríficas, así como un gimnasio con zona de masaje y sauna con solarium.\r\nLa zona exterior oferece un excelentemente cuidado parque ajardinado (con riego automático), amplio alumbrado exterior, un establo para caballos con 6 cuadras incluyendo agua y luz, una gran piscina y una pista de tenis.\r\nComo el hotel aún está abierto y por razones de discreción, no se puede publicar fotos y la ubicación exacta del hotel. Si ústed desea más información, póngase en contacto con nuestra oficina.'),
('54042','19106','22','a consultar'),
('54043','19107','22',Null),
('54044','19108','22',Null),
('54045','19109','22',Null),
('54046','19110','22',Null),
('54048','19112','1','16.Jahrhundert, renoviert 1998/99'),
('54049','19112','5','16th century, renovated 1998/99'),
('54050','19112','22','siglo XVI., reformado 1998/99'),
('54051','19113','1',Null),
('54052','19114','1',Null),
('54053','19115','1',Null),
('54054','19116','1',Null),
('54055','19117','1',Null),
('54056','19118','1',Null),
('54057','19119','1',Null),
('54058','19120','1',Null),
('54059','19121','1',Null),
('54060','19122','1',Null),
('54061','19123','1',Null),
('54062','19114','5',Null),
('54063','19113','5',Null),
('54064','19115','5',Null),
('54065','19116','5',Null),
('54066','19120','5',Null),
('54067','19118','5',Null),
('54068','19119','5',Null),
('54069','19117','5',Null),
('54070','19121','5',Null),
('54071','19122','5',Null),
('54072','19123','5',Null),
('54073','19114','22',Null),
('54074','19113','22',Null),
('54075','19115','22',Null),
('54076','19116','22',Null),
('54077','19120','22',Null),
('54078','19118','22',Null),
('54079','19119','22',Null),
('54080','19117','22',Null),
('54081','19121','22',Null),
('54082','19122','22',Null),
('54083','19123','22',Null);
