/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('89362','30770','1','Ein Juwel von Finca Nähe Calvia'),
('89363','30771','1','Im Randgebiet von Calvia im Südwesten Mallorcas, liegt dieser Finca Juwel auf einem ca 9.000m² großen Grundstück und wurde 2006 mit viel Liebe zum Detail saniert. Von hier aus sind es nur wenige Fahrminuten zu den Golfplätzen von Santa Ponsa, Supermärkten, Jachthäfen und internationale Schulen. \r\nÜber eine 150m lange Auffahrt, vorbei an einem parkähnlich angelegten mediterranen Garten, erreicht man den Car Port mit 5 überdachten Abstellplätzen. Die sehr gepflegte Finca besteht aus 2 Gebäuden.\r\nDas Haupthaus bietet auf dem EG Level die Eingangsdiele, 3 Schlafzimmer mit je einem Duschbad en suite, ein Badezimmer mit Wirlwanne und Dusche, Wohn-Esszimmer und eine Küche mit Frühstücksraum. Alle Küchengeräte sind von Bosch inklusive großer Kühlschrank mit Eismacher für die coolen Drinks.\r\nIm 1. OG befindet sich das Masterschlafzimmer mit Ankleide, Badezimmer mit Wanne und Dusche sowie 2 Terrassen. Abstellräume und ein Wäscheraum sind vorhanden.\r\nEin Gästehaus mit ca 40m² bietet ein Schlafzimmer, eine kleine Küche. \r\nVon mehreren überdachten Terrassen aus hat man einen wunderschönen Blick in den aufwendig gestalteten Garten mit sorgsam ausgesuchten heimischen Blumen, Sträuchern und Zitrusbäumen.\r\nIn kühleren Wintermonaten sorgt eine Ölzentralheizung- und im Sommer eine Klimaanlage für die richtige Raumtemperatur.\r\nEin Barbecue und der Aussenpool umgeben mit Liegeterrassen schließen das Angebot ab.\r\n'),
('89364','30772','1',Null),
('89365','30773','1',Null),
('89366','30774','1',Null),
('89367','30775','1',Null),
('89368','30776','1',Null),
('89370','30770','5','A gem of country house near Calvia'),
('89371','30771','5','In the outskirts of Calvia, in the southwest of Mallorca, stands this finca jewel on a 9.000m ² plot.  The Finca was renovated in 2006 with great attention to detail. From here it is only a short drive to the golf courses of Santa Ponsa, supermarkets, marinas and international schools.\r\nAbout a 150m long private driveway, past a park-like landscaped mediterranean garden, you reach the car port with 5 covered parking spaces. The well maintained property consists of 2 buildings.\r\nThe main house offers on the ground level the entrance hall, 3 bedrooms each with en suite bath room with shower, a bathroom with Jacuzzi and shower, living-dining room and a kitchen with a cosy breakfast room. All kitchen appliances are by Bosch including large fridge with ice maker for cool drinks.\r\nIn the first Floor is a master bedroom with dressing room, bathroom with tub and shower and 2 terraces. Storage rooms and a laundry room are available.\r\nA guest house with 40m ² has a bedroom and a small kitchen.\r\nSeveral covered terraces offers a beautiful view of the elaborate garden with carefully selected native flowers, shrubs and citrus trees.\r\nIn the cooler winter months, an oil fired central heating and in the warm summer an air condition provides a proper room temperature.\r\nA barbecue and the outdoor swimming pool, surrounded by sun terraces, complete the offer.\r\n'),
('89372','30772','5',Null),
('89373','30773','5',Null),
('89374','30774','5',Null),
('89375','30775','5',Null),
('89376','30776','5',Null),
('89378','30770','22','Una joya de casa de campo cerca de Calvia'),
('89379','30771','22','En las afueras de Calvià en el suroeste de Mallorca. Esta joya de finca se encuentra en una parcela de 9.000m ².  La finca se fue renovado en 2006 con gran atención al detalle. A partir de aquí es sólo un corto viaje a los 3 campos de golf de Santa Ponsa, supermercados , puertos deportivos y escuelas internacionales .\r\nSobre un camino largo 150m, más allá de un jardín paisajista mediterránea como un parque, se llega a la zona de parking con 5 plazas de aparcamiento cubierto. La propiedad consta de 2 edificios.\r\nLa casa principal ofrece en planta baja el hall de entrada, 3 dormitorios cada uno con baño propio con ducha, mas un baño con Jacuzzi y ducha, salón-comedor y una cocina con esquina de desayunos. Todos los aparatos de cocina son de marca Bosch incluyendo nevera con fabricador de hielo para las bebidas frías.\r\nEn la primera Planta está el dormitorio principal con vestidor, baño con bañera y ducha y 2 terrazas. \r\n2 almacenes y una lavandería tiene su propia entrada al exterior.\r\nUna casa de huéspedes con 40m ² cuenta con un dormitorio y una pequeña cocina.\r\nDesde varias terrazas cubiertas ofrecen una vista hermosa del elaborado jardín de flora autóctona cuidadosamente seleccionada, arbustos y árboles de cítricos.\r\nUna calefacción central asegura la temperatura adecuada.\r\nUna barbacoa y la piscina al aire libre rodeada de terrazas completan la oferta.\r\n'),
('89380','30772','22',Null),
('89381','30773','22',Null),
('89382','30774','22',Null),
('89383','30775','22',Null),
('89384','30776','22',Null),
('89386','30778','1',Null),
('89387','30779','1',Null),
('89388','30780','1','2006'),
('89389','30781','1',Null),
('89390','30782','1',Null),
('89391','30780','5','2006'),
('89392','30779','5',Null),
('89393','30778','5',Null),
('89394','30781','5',Null),
('89395','30782','5',Null),
('89396','30780','22','2006'),
('89397','30779','22',Null),
('89398','30778','22',Null),
('89399','30781','22',Null),
('89400','30782','22',Null);
