/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('73653','25539','1','Top-moderne Neubauvilla mit spektakulären Meerblick in der Cala Llamp/Port d‘Andratx'),
('73654','25540','1','Die Cala Llamp liegt nur 2 km vom beliebten Luxusyachthafen Port d‘Andratx entfernt. Die neu erbaute moderne Villa steht auf einem ca. 1.900 m² großen Hanggrundstück in Westlage und bietet einen fantastischen Meerblick. Der deutsche Bauherr legte großen Wert auf hochwertige Materialien und beste Bauqualität. Bei der Erstellung wurde nichts dem Zufall überlassen. Die ca. 1.330 m² bebaute Fläche teilt sich auf in Haupthaus, Gästehaus und separatem Gästeapartment.\r\nDas Haupthaus mit 2 Wohnetagen bietet im Obergeschoss zwei gleich große Schlafzimmer, jeweils mit Ankleiden, Bädern en suite und Terrasse. Im Erdgeschoss des Hauses befinden sich Wohn-Esszimmer, moderne Einbauküche, Vorbereitungsküche, temperierter Weinkeller, WC und ein Schlafzimmer mit Bad en Suite.\r\nIm Gästehaus befinden sich 2 Schlafzimmer mit je einem Bad en Suite. Zwischen Haupthaus und Gästehaus liegt der 5,5m x 10 m große Pool, ein Jacuzzi, eine Außenküche, überdachte Terrasse und ein Wellnessbereich mit Klaf Sauna, verschiedenen Duschen und Fitnessraum.\r\nDes Weiteren gibt es noch ein ca. 65 m² großes, separates Gäste Apartment mit Wohnzimmer, Küche, Schlafzimmer und Bad.\r\nZur hochwertigen technischer Ausstattung gehören u.a. Aluminium/Holz Schiebe Panoramafenster mit elektrischen Rollläden und Insektengitter, 4 Kamine (davon 3 Gaskamine), Klimaanlage, Fußbodenheizung (Wärmepumpe), installierte Musikanlage von simple audio /B&W, Loewe TV-Geräte in allen Schlafräumen,  BUS System von Gira für die komplette Steuerung aller elektrischen Anschlüsse und Geräte auch über iPhone/iPad, Alarmanlage u.v.m. Eine komplette Baubeschreibung erhalten Sie auf Anfrage. '),
('73655','25541','1',Null),
('73656','25542','1',Null),
('73657','25543','1',Null),
('73658','25544','1',Null),
('73659','25545','1',Null),
('73661','25539','5','Newly built, state-of-the-art villa with stunning sea views in Cala Llamp / Port d''Andratx'),
('73662','25540','5','Cala Llamp is situated just 2 kilometers away from the luxury marina of Port d''Andratx. The newly built modern style villa sits gloriously on a 1,900 m² west facing hillside plot and enjoys fantastic sea views. The German builder selected only first-class materials and attached great importance to a superior quality of construction.\r\nThe building area of approx. 1,330 m² is divided into the main house, guest house and a separate guest apartment.\r\nThe main house has 2 floors, the upper floor consists of two equal-sized bedrooms, each with dressing room, en suite bathrooms and terrace, on the ground floor are the living-dining room, modern fitted kitchen, tempered wine cellar, bathroom and bedroom with en suite bathroom.\r\nThe guest house offers 2 bedrooms, each with bathroom en suite. Between the main house and the guest house is located the swimming pool (5.5 m x 10 m), a Jacuzzi, a summer kitchen, covered terrace and a spa area with sauna (Klaf), several showers and a fitness room. The 65 m² guest apartment comprises of a living room, kitchen, bedroom and bathroom.\r\nQuality materials have been used throughout, complimented by the use of top of the range installations, luxury fittings & intelligent technical systems such as aluminum / wood sliding panoramic windows with electric blinds, 4 fireplaces (including 3 gas fireplaces), air conditioning, under floor heating (heat pump), installed music system from simple audio / B & W, TVs in all bedrooms (Loewe), full home automation system from Gira (can be operated also via iPhone / iPad), alarm system and many more. Complete specifications are available on request.'),
('73663','25541','5',Null),
('73664','25542','5',Null),
('73665','25543','5',Null),
('73666','25544','5',Null),
('73667','25545','5',Null),
('73669','25539','22','Nueva villa de alto standing con espectaculares vistas al mar en Cala Llamp / Port d''Andratx'),
('73670','25540','22','Cala Llamp está situado a sólo 2 kilómetros del exclusivo puerto deportivo de Port d''Andratx. Esta moderna villa de nueva construcción se encuentra en un terreno con pendiente de 1.900 m² con orientación al oeste y goza de unas fantásticas vistas al mar. El constructor alemán ha seleccionado sólo materiales de altísima calidad y la tecnología más moderna para crear una propiedad excepcional que colmará sus exigencias más especiales. \r\nLa superficie construida cuenta con unos 1.330 m² divididos en la casa principal, la casa de invitados y un apartamento de invitados.\r\nLa casa principal tiene 2 plantas, en la planta superior están dos dormitorios, cada uno con vestidor, baño en suite y terraza. La planta baja alberga un salón-comedor, una moderna cocina con antecocina, una bodega y un dormitorio con baño en suite.\r\nEn la casa de huéspedes hay 2 dormitorios, cada uno con baño en suite. Entre la casa principal y la casa de huéspedes se encuentra una piscina de 5,5 m x 10 m, un jacuzzi, una cocina de verano, una terraza cubierta y una zona de spa con sauna (Klaf), varias duchas y sala de fitness. Además, el apartamento de invitados con 65 m² dispone de un salón, una cocina, un dormitorio y un baño.\r\nLas instalaciones de primera calidad  incluyen: ventanas panorámicas correderas de aluminio / madera con persianas eléctricas, 4 chimeneas (incluyendo 3 chimeneas de gas), aire acondicionado, calefacción por suelo radiante (bomba de calor), sistema de sonido en el interior y exterior de la marca simple audio / B & W, televisores de Loewe en todas las habitaciones, domótica de la marca Gira para manejar todas las instalaciones eléctricas (incluso a través del iPhone / iPad), alarma centralizada y mucho más. Las especificaciones detalladas se puede solicitar por correo electrónico.'),
('73671','25541','22',Null),
('73672','25542','22',Null),
('73673','25543','22',Null),
('73674','25544','22',Null),
('73675','25545','22',Null),
('73677','25547','1','2013'),
('73678','25547','5','2013'),
('73679','25547','22','2013'),
('73680','25548','1',Null),
('73681','25549','1',Null),
('73682','25550','1',Null),
('73683','25551','1',Null),
('73684','25552','1',Null),
('73685','25553','1',Null),
('73686','25554','1',Null),
('73687','25555','1',Null),
('73688','25556','1',Null),
('73689','25557','1',Null),
('73690','25548','5',Null),
('73691','25549','5',Null),
('73692','25550','5',Null),
('73693','25551','5',Null),
('73694','25552','5',Null),
('73695','25554','5',Null),
('73696','25553','5',Null),
('73697','25555','5',Null),
('73698','25556','5',Null),
('73699','25557','5',Null),
('73700','25548','22',Null),
('73701','25549','22',Null),
('73702','25550','22',Null),
('73703','25551','22',Null),
('73704','25552','22',Null),
('73705','25554','22',Null),
('73706','25553','22',Null),
('73707','25555','22',Null),
('73708','25556','22',Null),
('73709','25557','22',Null);
