/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('89955','30969','1','Neue Luxus Apartmentanlage in 1. Meereslinie Portixol, Palma'),
('89956','30970','1','In der 1. Meereslinie in Palma de Mallorca entsteht zurzeit die 2. Bauphase einer schon bestehenden Apartmentanlage. Zum Stadtstrand von Palma sind es nur 2 Gehminuten. Mehrere Restaurants und chillige Beachbars befinden sich in unmittelbarer Nähe. \r\nDie Luxusapartments haben zwischen 155m² und 325m²  konstruierte Fläche die sich auf Wohn-Esszimmer, Küche, Hauswirtschaftsraum, 4 Schlafzimmer und 4 Badezimmer verteilt.  Das Hauptschlafzimmer hat zusätzlich noch einen begehbaren Kleiderschrank und Zugang zur Hauptterrasse mit Meerblick. Ein Gästeschlafzimmer hat eine kleinere Terrasse mit Stadtblick. Alle Apartments sind mit hochwertigen Materialien ausgestattet wie z.B. Weißlack Küchenmöbel, Waschmaschine und Trockner von Siemens, Induktionskochfeld, großer Kühlschrank, Gaggenau Geräte,  Klimaanlage w/k, Fußbodenheizung Wasser / Gas-Solar, elektrische Rollläden, Klimalit Doppelglasfenster u.v.m\r\nZu jeder Wohnung gehört ein Tiefgaragenplatz. Ein 2. kann je nach Verfügbarkeit dazu erworben werden. Alle Apartments sind bequem mit dem Lift zu erreichen. Die Penthouse Apartments haben zusätzlich noch eine Dachterrasse mit Wirlpool und Barbecue. Die Wohnanlage bietet noch zusätzlich im Außenbereich ein Pool, ein Tennisplatz und einen Kinderspielplatz an.\r\nPreise: von 1.280.000€ bis 2.500.000€ \r\nZahlungsmodalitäten.  \r\nBei Reservierungsvertrag:       Anzahlung  20% plus IVA\r\nWährend der Bauphase:         Teilzahlung 10% plus IVA\r\nBei Notartermin und Schlüsselübergabe:   70% plus IVA\r\n\r\n'),
('89957','30971','1',Null),
('89958','30972','1',Null),
('89959','30973','1',Null),
('89960','30974','1',Null),
('89961','30975','1',Null),
('89963','30969','5','New luxury apartment complex in 1st Sea line Portixol, Palma'),
('89964','30970','5','In the first Line to the sea of Palma de Mallorca is currently being the second construction phase, of an existing apartment complex, under construction. It’s only a 2 minute walk to the beautiful city beach of Palma. Several restaurants and chill out beach-bars are near by.\r\nThe luxury apartments have between 155m² and 325m² of living space spread over the living-dining room, kitchen, utility room, 4 bedrooms and 4 bathrooms. The master bedroom has an additional walk-in closet and access to the main terrace with sea views. One guest bedroom has a small terrace with city views. All apartments are equipped with high-quality materials such as white lacquer kitchen furniture, washer and dryer from Siemens, induction hob, large fridge, Gaggenau appliances, air conditioning hot / cold, under floor heating water / gas-solar, electric shutters, aluminum double glazed windows and much more.\r\nEach apartment has a underground parking space. A 2. can be purchased, subject to availability so. All apartments are easily accessible by elevator. \r\nThe penthouse apartments have additionally rooftop terraces with Jacuzzi and barbecue. The community offers a swimming pool, a tennis court and a children''s playground.\r\nPrices from 1.280.000€  to 2.728.000€\r\nPrices after finishing the construction:    from 1.280.000€  to  2.500.000€\r\nPayment arrangement.\r\nFor reservation contract:  payment 20% plus IVA \r\nDuring the construction phase: partial payment of 10% plus IVA \r\nAt Notary and key collection: 70% plus IVA\r\n'),
('89965','30971','5',Null),
('89966','30972','5',Null),
('89967','30973','5',Null),
('89968','30974','5',Null),
('89969','30975','5',Null),
('89971','30969','22','Nuevo complejo de apartamentos de lujo en primera Línea de mar, Portixol , Palma'),
('89972','30970','22','En la primera Línea de mar en Palma de Mallorca está siendo actualmente el segundo fase de un complejo de apartamentos existente. A la de la Playa de Palma son sólo 100 metros.\r\nLos apartamentos de lujo tienen entre 229m² y 239m² de superficie habitable distribuidos a través de la sala de estar - comedor, cocina, lavadero, 4 dormitorios y 4 baños. El dormitorio principal tiene un walk in closet y acceso a la terraza principal con vistas al mar. Un dormitorio de invitados tiene una pequeña terraza con vistas a la ciudad. Todos los apartamentos están equipados con materiales de alta calidad, tales como muebles de cocina de laca blanca, lavadora y secadora de marca Siemens, encimera de inducción, nevera grande, electrodomésticos Gaggenau, aire acondicionado f/k, calefacción por suelo radiante de agua /, gas – solar,  persianas eléctricas, ventanas acristalamiento doble, y mucho más.\r\nCada apartamento tiene una plaza de aparcamiento. Un 2 se pueden adquirir, sujeto a disponibilidad. Todos los apartamentos son de fácil acceso por ascensor. Los áticos tienen además una terraza en la azotea con jacuzzi y barbacoa. Fuera de la comunidad cerrada todavía ofrece una piscina, una pista de tenis y un parque infantil.\r\nLos precios: desde  1.280.000€  a  2.500.000 €\r\nModalidades de pago:\r\nPor contrato de reserva:  pago del 20% más IVA \r\nDurante la fase de construcción:  pago parcial de 10% más IVA \r\nCuando el Notario y recogida de llaves: 70% más IVA\r\n'),
('89973','30971','22',Null),
('89974','30972','22',Null),
('89975','30973','22',Null),
('89976','30974','22',Null),
('89977','30975','22',Null),
('89979','30977','1',Null),
('89980','30978','1','2015'),
('89981','30979','1',Null),
('89982','30980','1',Null),
('89983','30978','5',Null),
('89984','30977','5',Null),
('89985','30979','5',Null),
('89986','30980','5',Null),
('89987','30978','22',Null),
('89988','30977','22',Null),
('89989','30979','22',Null),
('89990','30980','22',Null);
