/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('94003','32367','1','Luxus Residenz in Son Vida zu verkaufen'),
('94004','32368','1','Son Vida ist eine wunderschön gelegene, bewachte Luxus Wohnlage, am Stadtrand von Palma de Mallorca. In unmittelbarer Nachbarschaft von 3 Golfplätzen und zwei 5 Sterne Hotels liegt diese Traumresidenz auf einem 7.345m² großen Grundstück. Von hier aus hat man einen fantastischen Panoramablick auf  Palma de Mallorca und auf die Berge von Son Vida. Diese Residenz ist absolut ruhig gelegen und lässt keine Wünsche offen. Sie bietet insgesamt 2.500m²  Wohnfläche. Über eine Einganshalle, im EG mit doppelter Raumhöhe und Galerie, betritt man das Haupthaus. Von hier aus hat man Zugang zu einem Kaminzimmer, Esszimmer, Küche mit Essecke, Bibliothek, Arbeitszimmer, Fernsehzimmer, Wohnzimmer, Masterschlafzimmer mit 2. kleineren Schlafzimmer mit Bad en suite, Ankleide und großzügigem Marmorbadezimmer.\r\nIm Untergeschoss befinden sich ein  Weinkeller, Fitnessraum, eine separate Angestellten Wohnung mit 2 Schlafzimmern, 2 Badezimmer und Wohnzimmer, Bügelraum, Abstellraum und Hauswirtschaftsraum.\r\nÜber eine Hollywoodtreppe erreicht man das 1. OG. Hier empfangen Sie ein Billardraum auf der Galerie, 3 Schlafzimmer und 3  Badezimmer en suite, sowie ein Büroraum mit Kamin. Alle Räume haben Zugang zu Terrassen.\r\nDas separat gelegene Gästehaus verfügt einen Spabereich mit Pool (12x3m), Sauna und eine Bar, sowie 2 Apartments im 1. OG mit je einem Schlafzimmer, Wohnzimmer, Küche und Badezimmer. Zur hochwertigen Ausstattung gehören u.a. Marmorfußböden. Klimaanlage w/k, Fußbodenheizung, Aufzug, Bose Sound System und vieles mehr.\r\nIm parkähnlich angelegten Außenbereich befinden sich ein südlich ausgerichteter Pool, Grillplatz, Tennisplatz, eine Garage für 4 Autos und offene Parkplätze. Ein 3.000m² großes angrenzendes Meerblick -Grundstück kann zusätzlich noch dazu erworben werden.\r\n'),
('94005','32369','1',Null),
('94006','32370','1',Null),
('94007','32371','1',Null),
('94008','32372','1',Null),
('94009','32373','1',Null),
('94011','32367','5','Luxury residence for sale in Son Vida'),
('94012','32368','5','Son Vida is a beautiful gated luxury residential area, on the outskirts of Palma de Mallorca. In the immediate neighborhood of 3 golf courses and two five star hotels, this dream residence is situated on a large plot 7.345m². From here you have a fantastic panoramic view of Palma de Mallorca and the mountains of Son Vida. This residence is absolutely quiet and leaves nothing to be desired. It offers a total of 2,500m² of living space. About the entrance hall on the ground floor with double height ceiling and gallery, one enters the main house. From here you have access to a salon with fireplace, dining room, kitchen with dining area, library, study, TV room, living room, master bedroom with smaller 2nd bedroom with bathroom en suite, dressing room and a spacious marble bathroom.\r\nIn the basement there is a wine cellar, exercise room, a separate staff apartment with 2 bedrooms, 2 bathrooms, 2 kitchen and living room, ironing room, storage room and laundry room.\r\nA Hollywood staircase leads you to the first floor. Here you receive a billiards table in the loft. Further you have 3 bedrooms and 3 bathrooms en suite, and an office room with fireplace. All rooms have access to terraces.\r\nThe separately located guest house offers a spa area with swimming pool (12x3m), a sauna and a bar, as well as 2 apartments on the 1st floor each one with one bedroom, living room, kitchen and bathroom. The high quality facilities includes,  marble floors. air condition system w / c, under floor heating,  lift, Bose sound system and much more.\r\nIn the park-like outdoor area includes a south facing pool, barbecue area, tennis court, garage for 4 cars and open parking places. \r\nA 3,000m² large sea view nabor plot can be additionally purchased\r\n'),
('94013','32369','5',Null),
('94014','32370','5',Null),
('94015','32371','5',Null),
('94016','32372','5',Null),
('94017','32373','5',Null),
('94019','32367','22','Residencia de lujo en venta en Son Vida'),
('94020','32368','22','Son Vida es un lugar hermoso, en una zona residencial de lujo y vigilada, a las afueras de Palma de Mallorca. En la vecindad inmediata hay 3 campos de golf y dos hoteles de cinco estrellas. Esta residencia de ensueño se encuentra en una gran parcela de 7.345m². Desde aquí se tiene una fantástica vista panorámica de Palma de Mallorca y las montañas de Son Vida, ademas es muy tranquila y no deja nada que desear. Dispone de un total de 2.500 m² de espacio habitable. Entras en un hall de entrada en la planta baja con techo de doble altura y una galería. Desde aquí se tiene acceso a un salon con chimenea, comedor, cocina con comedor, biblioteca, estudio, sala de televisión, sala de estar, dormitorio principal con pequeño segundo dormitorio con baño en suite, vestidor y un amplio baño de mármol.\r\nEn el sótano hay una bodega, sala de ejercicios, un apartamento separado con 2 dormitorios, 2 baños y sala de estar, cuarto de plancha, trastero y lavadero.\r\nUna escalera de Hollywood lleva a la primera planta. Aquí usted recibe un mesa de Billard en la galeriea, 3 dormitorios y 3 baños en suite, y una sala de oficina con chimenea. Todas las habitaciones tienen acceso a terrazas.\r\nLa casa de huéspedes ubicada por separado ofrece una zona de spa con piscina interior (12x3m), una sauna y un bar, así como 2 apartamentos de la primera planta cada uno con un dormitorio, sala de estar, cocina y baño. Los instalaciones de alta calidad incluyen entre otras, suelos de mármol, calefaccion de suelo, aire acondicionado f / c, ascensor, sistema de sonido „Bose“ y mucho más.\r\nEn la zona al aire libre esta como un parque botanico con piscina, zona de barbacoa, pista de tenis, garaje para 4 coches y aparcamientos. Un solar adyacente con 3.000m²  y vista al mar esta tambien en venta.\r\n'),
('94021','32369','22',Null),
('94022','32370','22',Null),
('94023','32371','22',Null),
('94024','32372','22',Null),
('94025','32373','22',Null),
('94027','32375','22','1998'),
('94028','32375','5','1998'),
('94029','32375','1','1998'),
('94030','32376','1',Null),
('94031','32377','1',Null),
('94032','32378','1',Null),
('94033','32379','1',Null),
('94034','32377','5',Null),
('94035','32376','5',Null),
('94036','32378','5',Null),
('94037','32379','5',Null),
('94038','32377','22',Null),
('94039','32376','22',Null),
('94040','32378','22',Null),
('94041','32379','22',Null);
