/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('96936','33456','1','Exklusives Landhotel im Herrenhausstil zu verkaufen'),
('96937','33457','1','Dieses Herrenhaus zum Träumen ist ein sehr gepflegtes Anwesen mit einem Grundstück von 48.500 m² und ruht im wahrsten Sinne des Wortes auf einer riesigen Orangenplantage mit einzigartigem Charme. Hier kommen Sie nicht einfach an, hier fühlen Sie sich gleich wie zuhause – und werden schnell gefangen vom Duft der Orangenblüten. Eine himmlische Ruhe umgibt die im englischen Stil gehaltene Residenz mit einer Wohnfläche von 1.277 m² und insgesamt 12 Schlafzimmer mit jeweils Bad en suite, teilweise mit Kamin und eigener Terrasse in den Orangenhain hinein und mit allem zeitgemäßen Komfort ausgestattet. Spektakulär ist sicher die Turmsuite über 2 Etagen mit atemberaubendem Panoramablick. Das ganze Haus ist mir viel Liebe zum Detail eingerichtet. Ausgewählte Antiquitäten und Accessoires, spannende Kunst an den Wänden und edle Holzfussböden schaffen eine ländlich-elegante Atmosphäre. Die verschiedenen Terrassen bieten viel Platz und der Poolbereich lädt zum Sonnenbaden ein. Des Weiteren verfügt das Anwesen über Fitnessraum, Weinkeller, Büro, verschiedene Arbeitsräume, Kühlhäuser und separate Wohnbereich für das Personal.\r\nEine hochwertige Ausstattung mit Wasserfiltersystem, Osmosegerät, Entkalkungsanlage, Wasserbrunnen, automatische Bewässerungsanlage und Alarmsystem gehört zum Anwesen, ebenso wie ein überdachter Carport für 5 Pkws und großer Parkplatz.\r\nDas Hotel hat eine Lizenz für ein Hotel rural, kann aber auch als private Residenz genutzt werden\r\n'),
('96938','33458','1',Null),
('96939','33459','1',Null),
('96940','33460','1',Null),
('96941','33461','1',Null),
('96942','33462','1',Null),
('96944','33456','5','Exclusive Mansion in Palma with lots of charm and all extras of a dreamlike property'),
('96945','33457','5','This truly dreamlike Mansion is a very well maintained property on a plot of 48.500 m² and rests in the truest sense within a huge orange grove with unique charm. Here you’re not just arriving; here you will feel right at home - and quickly caught by the scent of orange blossoms. A heavenly silence surrounds the English-style residence with a floor space of 1277 m² and a total of 12 bedrooms, each equipped with bathroom en suite and with every modern comfort, some with fireplace and private terrace into the orange grove. Certainly spectacular is the tower suite, spread over 2 floors and with breathtaking panoramic views. The entire house is decorated with a lot of attention to detail. Selected antiques and accessories, exciting art on the walls and elegant wooden floors create a rustic, yet elegant atmosphere. The various terraces offer plenty of room and the pool area is ideal for sunbathing. Further on, the property provides for a gym, wine cellar, office, several study rooms, cold storage facilities and a separate living area for staff.\r\nHigh-quality equipment with water filtering system, osmosis unit and decalcification, water fountains, automatic irrigation and alarm system are part of the property, as well as a roofed carport for 5 cars and ample parking.\r\nThis Hotel has a license for hotel rural but can also be used as a private villa\r\n'),
('96946','33458','5',Null),
('96947','33459','5',Null),
('96948','33460','5',Null),
('96949','33461','5',Null),
('96950','33462','5',Null),
('96952','33456','22','Hotel rural cerca de Palma con 12 habitaciones en venta'),
('96953','33457','22','La casa señorial de ensueño es una propiedad de alto nivel con un terreno de 48.500 m² y descansa, en el más puro sentido de la palabra, sobre una enorme plantación de naranjos con un ambiente único. Aquí la persona no sólo llega, sino que se siente inmediatamente como en casa, cautivado al instante por el perfume de la flor de azahar. Una tranquilidad infinita rodea la Residencia que conserva su estilo inglés y ofrece un ambiente lleno de lujo y dispone de una superficie de vivienda de 1.277 m² con 12 dormitorios con baño en suite cada uno, en parte con chimenea y terraza privada al naranjal. La suite de la torre, repartida en dos niveles, resulta verdaderamente espectacular con la vista panorámica. Toda la casa está decorada con mucho amor por los detalles. Una selección de antigüedades y accesorios, fascinantes obras de arte en las paredes y suelos nobles de madera crean una atmósfera rústica elegante. Las varias terrazas ofrecen mucho espacio y la piscina invita para disfrutar los días de sol. Además la propiedad dispone de una sala de gimnasio, bodega, oficina, trasteros, coladuría, almacenamientos en frío y viviendas separadas para el personal.\r\nEl equipamiento de alta calidad con sistema de filtro de agua, sistema de ósmosis y descalcificación, pozo de agua propio, riego automático y  sistema de alarma pertenece a la propiedad, así como un porche para 5 coches y un aparcamiento grande.\r\nEste hotel tiene una licencia para un hotel rural, pero se puede también utilizar come residencia privada.\r\n'),
('96954','33458','22',Null),
('96955','33459','22',Null),
('96956','33460','22',Null),
('96957','33461','22',Null),
('96958','33462','22',Null),
('96960','33464','1',Null),
('96961','33465','1',Null),
('96962','33466','1',Null),
('96963','33467','1',Null),
('96964','33465','5',Null),
('96965','33464','5',Null),
('96966','33466','5',Null),
('96967','33467','5',Null),
('96968','33465','22',Null),
('96969','33464','22',Null),
('96970','33466','22',Null),
('96971','33467','22',Null);
