/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('97855','33770','1','Beeindruckende Villa mit herrlicher Aussicht aufs Meer und über den Golfplatz von Bendinat'),
('97856','33771','1','Diese exklusive Villa mit einer Wohnfläche von 600m² befindet sich auf einem südwestorientierten, automatisch bewässerten Gartengrundstück von 2148m² in begehrter Villenwohnlage oberhalb der königlichen Golfanlage von Bendinat. Von hier aus sind es nur wenige Autominuten Nobelhafen Portals Nous und nach Palma de Mallorca.\r\nDie Luxusvilla wurde im Neoklassizistischen Stil erbaut. Ausgestattet mit hochwertigen  Materialien, besticht die Villa durch eine durchdachte und praktische Raumaufteilung. Über den Haupteingang im Erdgeschoss betritt man eine eindrucksvolle Wohnhalle mit Kamin und einem eleganten Treppenaufgang aus Marmor. Des Weiteren befinden sich auf der EG Ebene ein Esszimmer, eine Küche mit Hauswirtschaftsraum, Zugang zur Garage, ein Wintergarten mit Meerblick, eine Schlafzimmersuite und ein Gäste-WC. Im 1. OG befinden sich zwei Gäste  Schlafzimmer mit Ankleide und 2 Badezimmer, ein Büroraum, eine große Bibliothek,  ein Master Schlafzimmer mit Ankleide und elegantem, mit hochwertigen Marmor ausgestatteten Badezimmer. Von den meisten Zimmern hat man Zugang zu einer Terrasse. Die Villa ist umgeben von einem mediterranen Garten, und bietet durch die erhöhte Lage einen traumhaften Blick auf die Bucht von Palma und das offene Meer. Im Keller gibt es einen Abstellraum und ein Technikraum für die Ölzentralheizung. Zur weiteren technischen Ausstattung gehören ein zentrales Staubsauger System und eine zentrale Klimaanlage w/k\r\n'),
('97857','33772','1',Null),
('97858','33773','1',Null),
('97859','33774','1',Null),
('97860','33775','1',Null),
('97861','33776','1',Null),
('97863','33770','5','Impressive villa with magnificent views of the sea and over the golf course in Bendinat'),
('97864','33771','5','This exclusive villa with a floor space of 600m² is located on a southwest oriented plot of 2148m² in Bendinat. From here there are only a few minutes drive to the famus Marina of Portals Nous and city of Palma de Mallorca.\r\nThe luxury villa was built 1996 in the neoclassical style. Equipped with high quality materials. The main entrance on the ground floor one enters an impressive living room with fireplace and an elegant marble staircase to the 1st floor. on this level you´ll find also a dining room, a kitchen with utility room, access to the garage, a winter garden with sea views, a bedroom suite and a guest toilet. On the 1st floor there are two guest bedrooms with dressing rooms and 2 bathrooms, a smaller office space, a large library, a master bedroom with dressing room and elegant bathroom, equipped with high-quality marble. From most rooms you have access to a spacius terrace. The villa is surrounded by a beautifull maintained mediterranean garden, and offers an elevated position a fantastic with view over the bay of Palma and the sea. In the basement there is a storage room and a utility room for the oil central heating. For further technical equipment includes a central vacuum cleaner system and central air conditioning h / c\r\n'),
('97865','33772','5',Null),
('97866','33773','5',Null),
('97867','33774','5',Null),
('97868','33775','5',Null),
('97869','33776','5',Null),
('97871','33770','22','Impresionante villa con magníficas vistas al mar y al campo de golf de Bendinat'),
('97872','33771','22','Esta exclusiva villa, con una superficie de 600m² habitable, esta  situado en en Bendinat en un solar de 2148m² con orientacion suroeste con vista al Mar. Desde aquí hay sólo unos pocos minutos al puerto de Portals Nous y Palma de Mallorca.\r\nLa villa de lujo, construido en el estilo neoclásico, esta equipado con materiales de alta calidad y ofrece un plano de distrubucion muy práctico. La entrada principal en la planta baja se entra en una impresionante sala de estar con chimenea y una elegante escalera de mármol a la primera planta. Ademas hay en esta planta un comedor, una cocina con lavadero, acceso al garaje, una terraza acristalada con vistas al mar, un dormitorio en suite y un aseo. En la primera planta hay dos dormitorios de invitados con vestidor y 2 baños, un espacio de oficina, una gran biblioteca, un dormitorio principal con vestidor y un baño elegante, equipado de mármol de alta calidad. La mayoría de las habitaciones tiene acceso a una terraza grande. La villa está rodeada por un jardín mediterráneo con una systema riego automático, y ofrece una posición elevada una fantástica vista sobre la bahía de Palma y el mar. En el sótano hay un trastero y un lavadero para la calefacción central de gasoil. Para más equipamiento técnico incluye un sistema de aspiradora central y central de aire acondicionado frío / calor\r\n'),
('97873','33772','22',Null),
('97874','33773','22',Null),
('97875','33774','22',Null),
('97876','33775','22',Null),
('97877','33776','22',Null),
('97879','33778','22','2007'),
('97880','33778','5','2007'),
('97881','33778','1','2007'),
('97882','33779','1',Null),
('97883','33780','1',Null),
('97884','33781','1',Null),
('97885','33782','1',Null),
('97886','33780','5',Null),
('97887','33779','5',Null),
('97888','33781','5',Null),
('97889','33782','5',Null),
('97890','33780','22',Null),
('97891','33779','22',Null),
('97892','33781','22',Null),
('97893','33782','22',Null);
