/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('91410','31484','1','Hotel mit 24 Zimmer zum Sanieren in 1. Meereslinie'),
('91411','31485','1','Dieses Hotel liegt direkt an einer Strandpromenade mit Badestrand in einem sehr beliebten Ferienort.\r\nDas Hotel steht auf einem ca 250m² grossen Grundstück mit ca 1.000m€ Wohn-Nutzfläche plus 200m2 Kellergeschoss. \r\nIm Erdgeschoss befindet sich die Rezeption mit Frühstücksraum, 4 Etagen mit 24 Zimmer mit Bad en suite, Dachterrasse für chill out lounge und Kellergeschoss für Personal Umkleide und Abstellräume\r\nDer Eigentümer begann bereits 2013 mit den Sanierungsarbeiten und hat es zu ca 75% fertig erstellt. Versorgungsleitungen für Strom und Wasser sind bereits verlegt. Ebenso die Klimaanlage ist vorinstalliert. Die Fenster (Alu- Doppelverglasung) sind eingebaut. Es fehlen noch Türen, Schränke, Waschbecken, Duschkabinen, Boden- und Badefliesen sowie Mobiliar. Ein älterer Aufzug müsste ausgetauscht werde. Sehr interessantes Objekt für jemand der gerne ein Boutique Hotel mit Übernachtung und Frühstück erwerben möchte. Der Preis wurde reduziert und ist nicht mehr verhandelbar.\r\n'),
('91412','31486','1',Null),
('91413','31487','1',Null),
('91414','31488','1',Null),
('91415','31489','1',Null),
('91416','31490','1',Null),
('91418','31484','5','Hotel with 24 rooms for refurbishment in the first sea line '),
('91419','31485','5','This hotel is right on a beach promenade of a very popular tourist resort. \r\nThe plot has approx 250m² and the constructed area approx. 1.000m² and 200m² basement for storage, staff toilets and changing rooms. 24 room are distributed over 4 stores. A nice chill out lounge cold be created on the roof terrace with spectacular sea views.\r\nThe hotel has a hotel license. The owner started in 2013 to rehabilitate and is created ready to approximately 75%. Supply lines for electricity and water are already laid. Also, the air conditioning is pré installed. The windows (aluminum double glazing) are installed. It still lacks doors, cabinets, sinks, shower stalls, floor tiles and furniture. An elderly elevator will have to replaced. Very interesting object for someone who would like to acquire a with bed and breakfast boutique hotel. \r\nThe price has been reduced and is no longer negotiable.\r\n'),
('91420','31486','5',Null),
('91421','31487','5',Null),
('91422','31488','5',Null),
('91423','31489','5',Null),
('91424','31490','5',Null),
('91426','31484','22','Hotel con 24 habitaciones por reformas en la primera línea de mar, Mallorca '),
('91427','31485','22','Este hotel está justo en un paseo con una playa en un pueblo turístico muy popular.\r\nEl hotel está situado en una parcela de aprox. 250m ² con aprox 1.000 m² superf.constr.,  mas 200m²  de sótano.\r\nEn la planta baja se encuentra la recepción con sala de desayuno, de 4 plantas con 24 habitaciones con baño completo, terraza de azotea para un chill-out lounge y el sótano para el personal de cambio y almacenamiento\r\nEl propietario comenzó a renovar en 2013 con las obras de renovación y se ha creado completamente a aproximadamente 75 %. Las líneas de suministro de electricidad y agua ya están establecidas. Además, hay una preinstalación de  aire acondicionado. Se instalan los ventanas (aluminio con doble acristalamiento). Todavía carece de puertas, armarios, lavabos, duchas, suelo y azulejos de baño y muebles. Un ascensor anciano tendrá que reemplazar. Muy interesante objeto para alguien que quisiera adquirir un hotel boutique con alojamiento y desayuno. El precio se ha reducido y ya no es negociable.\r\n\r\n'),
('91428','31486','22',Null),
('91429','31487','22',Null),
('91430','31488','22',Null),
('91431','31489','22',Null),
('91432','31490','22',Null),
('91434','31492','1',Null),
('91435','31493','1',Null),
('93089','31492','5',Null),
('93090','31493','5',Null),
('93091','31492','22',Null),
('93092','31493','22',Null);
