/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('95726','33021','1','Luxuriöse Villa mit tollem Meerblick in Son Vida'),
('95727','33022','1','Son Vida liegt nur 3km von Palma de Mallorca entfernt und gehört zu den Luxus Wohnlagen auf Mallorca. In unmittelbarer Nähe befinden sich 3 Golfplätze und zwei 5 Sternehotels.\r\nDie Villa steht auf einem 2.000m² großen Grundstück mit einem fantastischen Panoramablick auf die Stadt Palma und das Meer. Die ca 900m² Wohnfläche verteilt sich auf das Haupthaus und ein separates Gästeapartment (zurzeit 80m² Büro-Konferenzraum) sowie einen Fitnessraum und einen Schmucken Weinkeller. Alle Zimmer haben Meerblick und sind mit hochwertigen Materialien ausgestattet, wie z.B. Marmor Fußböden, Fußbodenheizung(Öl/Wasser), Klimaanlage, Lift, Alarmsystem mit Kameras innen und außen u.v.m. Die Villa befindet sich in einem guten Zustand und wird teilmöbliert verkauft. Über die großzügig gestaltete Eingangshalle in der oberen Etage erreicht man das Wohn-Esszimmer mit Kamin und überdachte Terrasse, eine Küche mit Zugang zum Barbecue bereich, ein Hauptschlafzimmer mit kleinem Salon, Bad und Ankleide, Zugang zur Garage, Gäste WC und einen Hauswirtschaftsraum. Auf der unteren Etage (Pool-Level) befinden sich 3 weitere Schlafzimmer mit je einem Badezimmer en suite, ein Meditationsraum und eine Sauna mit Jacuzzi im Außenbereich. Ein Pool mit offenen und überdachten Liegeterrassen schließt das Angebot ab. Top Villa – Top Lage - Super Preis!!\r\n'),
('95728','33023','1',Null),
('95729','33024','1',Null),
('95730','33025','1',Null),
('95731','33026','1',Null),
('95732','33027','1',Null),
('95734','33021','5','Luxury villa with stunning sea views in Son Vida'),
('95735','33022','5','Son Vida is located just 3 km from Palma de Mallorca and is one of the luxury residential areas in Mallorca. In the immediate vicinity there are 3 golf courses and two 5 star hotels.\r\nThe villa stands on over 2,000m² plot with fantastic panoramic views of the city of Palma and the sea. The approximately 900m² living space is spread over the main house and a separate guest apartment (currently 80m² office and conference room) as well as a gym and a charming wine cellar. All rooms have sea views and are equipped with high-quality materials, such as marble floors, underfloor heating (oil / water), air conditioning, lift, alarm system with cameras interior and exterior and many more. The villa is in good condition and will be sold partly furnished. About the generously proportioned entrance hall on the upper floor you can reach the living room with fireplace and covered terrace, a kitchen with access to the barbecue area, a master bedroom with lounge, bathroom and dressing room, access to the garage, guest toilet and a utility room. On the lower floor (pool level) are 3 further bedrooms with a bathroom en suite, a meditation room (japaneese style) and a sauna with outdoor located Jacuzzi. A pool with open and covered sun terraces completes the offer. Top Villa - Top location - Super Price !!\r\n'),
('95736','33023','5',Null),
('95737','33024','5',Null),
('95738','33025','5',Null),
('95739','33026','5',Null),
('95740','33027','5',Null),
('95742','33021','22','Villa de lujo con vistas al mar en Son Vida'),
('95743','33022','22','Son Vida se encuentra a sólo 3 km de Palma de Mallorca y es una de las zonas residenciales de lujo lo mas populares en Mallorca. En las inmediaciones hay 3 campos de golf y dos hoteles de 5 estrellas.\r\nLa villa se sitúa en una parcela de mas de 2.000 m² con fantásticas vistas panorámicas de la ciudad de Palma y el mar. La superficie construida de aproximadamente 900m² se distribuye en la casa principal, un casa de meditacion(30m²) y un apartamento independiente para invitados (actualmente 80m² sala de conferencias de oficina), así como un gimnasio y alrededor de una encantadora bodega de vinos. Todas las habitaciones tienen vistas al mar y están equipadas con materiales de alta calidad, tales como suelos de mármol, calefacción por suelo radiante (gasoil / agua), aire acondicionado, chiminea, ascensor, sistema de alarma con cámaras interiores y exteriores y muchos más La villa se encuentra en buenas condiciones y se vende parcialmente amueblado. Sobre el hall de entrada de generosas proporciones en la planta superior se puede llegar a la sala de estar con chimenea y terraza cubierta, cocina con acceso a la zona de barbacoa, un dormitorio principal con sala de estar, baño y vestidor, acceso al garaje, aseo y un lavadero. En la planta (nivel de la piscina) inferior a 3 dormitorios con baño en suite, una sala de meditación y una sauna con jacuzzi situado al aire libre. Una piscina con terrazas abiertas y cubiertas completa la oferta. Top Villa - Top Ubicación  - Super Precio !! \r\n'),
('95744','33023','22',Null),
('95745','33024','22',Null),
('95746','33025','22',Null),
('95747','33026','22',Null),
('95748','33027','22',Null),
('95750','33029','22','1996'),
('95751','33029','5','1996'),
('95752','33029','1','1996'),
('95753','33030','1',Null),
('95754','33031','1',Null),
('95755','33032','1',Null),
('95756','33033','1',Null),
('95757','33031','5',Null),
('95758','33030','5',Null),
('95759','33032','5',Null),
('95760','33033','5',Null),
('95761','33031','22',Null),
('95762','33030','22',Null),
('95763','33032','22',Null),
('95764','33033','22',Null);
