/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('37877','13534','1','Außergewöhnliche Luxus-Villa der Superlative in exklusiver Lage in Santa Ponsa'),
('37878','13535','1','Diese extravagante Villa, die zu einer der exklusivsten Immobilien im Mittelmeerraum gehört,  liegt in ruhiger Top-Lage, nur wenige Autominuten vom noblen Yachthafen Port Adriano entfernt. In unmittelbarer Nähe befinden sich außerdem fünf schöne Golfplätze. \r\nVon allen Räumen aus kann man einen spektakulären und unverbaubaren Süd/West-Meerblick genießen. Das Grundstück und die Terrassen  der Villa sind nicht einsehbar. Die weitläufigen Terrassen sind aus allen Räumen direkt begehbar. Das prachtvolle Anwesen hat annähernd 1000m² Wohn-/Nutzfläche und verfügt über einen großen, offenen Wohn- und Essbereich, eine moderne und exklusive Kugelküche, fünf große Schlafzimmer mit jeweils Jacuzzi & Dusche sowie Ankleide und zwei weitere große, repräsentative Räume. Des Weiteren gibt es eine Garderobe, einen Sicherheitsraum, ein Gäste-WC, extra Ankleideraum sowie mehrere Wirtschaftsräume und Keller.\r\nEin separates Apartment mit getrenntem Eingang, moderner Küche, Wohnzimmer, Schlafzimmer und Bad kann für Gäste oder Personal genutzt werden. Bei Bedarf bietet das Anwesen bis zu acht mögliche Schlafzimmer.\r\nWeitere Highlights dieser außerordentlichen Immobilie sind die zwei terrassenartig übereinander angeordneten großen Pools, das Outside-Jacuzzi und der Panorama-Aufzug. Die Villa biete eine geräumige Garage für zwei Autos und Stellplätze für weitere fünf Autos.\r\nDie Villa wurde mit den wertvollsten und edelsten Materialien erbaut. In den Pools und im Haus wurden über siebzig Quadratmeter 24 Kt. Gold verarbeitet.\r\nAngefangen von goldenen Armaturen und Kristallleuchtern bis hin zur modernen, extravaganten Küche wurde alles von Spezialisten eingebaut. Modernste Technik und Sicherheitseinrichtungen genügen höchsten Ansprüchen und sind dennoch einfach zu bedienen. Marmortechniken, Vergoldungen und Wandgemälde runden diese Luxus-Villa ab. Sollten Sie weitere Informationen wünschen, senden Sie uns bitte Ihre Postanschrift und eine Festnetznummer, damit wir Sie direkt kontaktieren können.'),
('37879','13536','1','auf Anfrage'),
('37880','13537','1',Null),
('37881','13538','1',Null),
('37882','13539','1',Null),
('37883','13540','1',Null),
('37885','13534','5','Exceptional superlative luxury villa in exclusive location in Santa Ponsa '),
('37886','13535','5','This extravagant villa, which is one of the most exclusive real estate properties in the Mediterranean, is situated in a quiet top location, just a few minutes drive away from the prestigious marina of Port Adriano. Five beautiful golf courses are in direct proximity. From every room you will enjoy spectacular and unobstructed South-West sea views. The plot and the terraces of the villa are not visible from the outside. The large terraces are directly accessible from every room. \r\nThis magnificent property has a living space of approximately 1000m ² and wide and open living and dining room, a modern and exclusive spherical kitchen, five large bedrooms, each with Jacuzzi and shower as well as dressing room and two further large, representative rooms. Furthermore, there is a cloak room, a panic room, a guest toilet, extra dressing room and several storage rooms and a cellar. \r\nAn apartment with separate entrance, modern kitchen, living room, bedroom and bath can be used for guests or staff. If necessary, the property offers up to eight bedrooms. \r\nAnother highlight of this extraordinary residence are two large exclusive superimposed swimming pools, the outside-Jacuzzi as well as the panoramic lift. The villa offers a spacious two-car garage and parking space for another five cars. \r\nThe villa is very solidly built, using the most precious and finest materials. Over 70m² 24-carat gold was used in the swimming pools and on the house itself. Everything, from the gold fixtures and crystal chandeliers to the modern and extravagant kitchen was all installed by specialists. The most modern technology and safety equipment meet even the highest expectations, while still being easy to operate. Marble, gold plating and murals round off this luxury villa.If you would like to have more information about the property, please send us an email with your postal address and a landline number and we will contact you directly.'),
('37887','13536','5','on request'),
('37888','13537','5',Null),
('37889','13538','5',Null),
('37890','13539','5',Null),
('37891','13540','5',Null),
('37893','13534','22','Extraordinaria y única villa de lujo en exclusiva zona en Santa Ponsa '),
('37894','13535','22','Esta extraordinaria villa, que es una de las casas más exclusivas en el Mediterráneo, está situado en una tranquila y deseada zona, a solo unos minutos del noble puerto náutico de Port Adriano. Cinco campos de golf están también muy cerca. \r\nDesde todas las habitaciones se puede disfrutar unas espectaculares vistas al mar sin obstáculos, dirección sur-oeste. El terreno y las terrazas de la villa no se puede ver desde fuera. Las amplias terrazas se puede acceder directamente desde todas las habitaciones. \r\nLa magnífica propiedad tiene una superficie habitable de unos 1000m ² y cuenta con un amplio salón-comedor, una moderna y exclusiva cocina de esférica, cinco grandes dormitorios, cada uno con jacuzzi & ducha y vestidor, y dos grandes y representativos cuartos. Además, hay una guardarropa, un panic room, un aseo, un vestidor así como varios trasteros y un sótano. \r\nUn apartamento independiente con cocina moderna, salón, dormitorio y cuarto de baño se puede utilizar para los huéspedes o el personal. Si es necesario, la propiedad ofrece un máximo de ocho dormitorios. \r\nUnas de las atracciones más importantes de esta extraordinaria villa son las grandes piscinas en dos niveles, el jacuzzi a fuera y el ascensor panorámico. La villa dispone de un amplio garaje para dos coches y además aparcamiento para cinco coches mas. \r\nLa villa fue construida con los materiales más valiosos y más finos. Sobre más de 70m² de la piscina y la casa se ha trabajado con oro de 24 quilates. \r\nDesde las griferías doradas y arañas de cristal hasta la moderna y extravagante cocina, toda la decoración interior fue instalada por especialistas. La más moderna tecnología e instalaciones de seguridad cumplen los estándares más altos y son, sin embargo, fácil de manejar. Mármol, dorados y pinturas completan esta mansión de lujo. Si quiere más información, por favor envíenos un email indicando su dirección postal y un número de teléfono fijo y nos pondrémos en contacto con Usted inmediatamente.\r\n'),
('37895','13536','22','a consultar'),
('37896','13537','22',Null),
('37897','13538','22',Null),
('37898','13539','22',Null),
('37899','13540','22',Null),
('37901','13542','1','2009 komplett renoviert'),
('37902','13542','5','2009 completely renovated'),
('37903','13542','22','2009 renovada completamente'),
('37904','13543','1',Null),
('37905','13544','1',Null),
('37906','13545','1',Null),
('37907','13546','1',Null),
('37908','13544','5',Null),
('37909','13543','5',Null),
('37910','13545','5',Null),
('37911','13546','5',Null),
('37912','13544','22',Null),
('37913','13543','22',Null),
('37914','13545','22',Null),
('37915','13546','22',Null),
('46477','16543','1',Null),
('46478','16544','1',Null),
('52402','18572','1',Null),
('52403','18572','5',Null),
('52404','18572','22',Null),
('52405','18573','1',Null),
('52406','18573','5',Null),
('52407','18573','22',Null),
('55528','16543','5',Null),
('55529','16544','5',Null),
('55530','16543','22',Null),
('55531','16544','22',Null);
