/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('79092','27348','1','Schönes Landhaus in der Sierra de Tramuntana '),
('79093','27349','1','Inmitten der wild romantischen Gebirgslandschaft der Sierra de Tramuntana, in einem kleinen, friedlichen Dörfchen erwartet Sie ein beschauliches Landhaus in perfektem Zustand. Das Haus bietet sieben große, schön eingerichtete  Schlafzimmer, die alle über Bädern en suite verfügen. Zur Ausstattung gehören Klimaanlage, Zentralheizung und Satellitenfernsehen.\r\nDie Immobilie wurde geschmackvoll im landestypischen Stil eingerichtet, der den Charme des alten Spaniens widerspiegelt.  \r\nDas ursprüngliche Gebäude, mit zwei maurischen Türmen, wurde von einheimischen Handwerkern umsichtig renoviert, sodass nichts vom traditionellen Charakter verloren ging und gleichzeitig jeder moderne Komfort geboten wird. \r\nZum Anwesen gehört außerdem noch eine großzügige Wohnung mit Wohnzimmer, zwei Schlafzimmern und Badezimmer. Eingebettet im mediterran angelegten Garten liegt ein Pool mit Liegeterrassen.\r\nDas Anwesen wurde bisher als Landhotel genutzt.'),
('79094','27350','1',Null),
('79095','27351','1',Null),
('79096','27352','1',Null),
('79097','27353','1',Null),
('79098','27354','1',Null),
('79100','27348','5','Beautiful country house in the Sierra de Tramuntana'),
('79101','27349','5','In the midst of the wild romantic landscape of the Sierra de Tramuntana, in a small and peaceful village you will find this lovely country house, which is in a perfect condition.\r\nThis house offers seven spacious, lovely decorated bedrooms, all equipped with en suite bathrooms. The house features air conditioning, central heating and satellite television. The luxurious rooms are tastefully decorated in Mediterranean style, reflecting the charm of old Spain. The original building, with two Moorish towers, has been carefully restored by local craftsmen, maintaining its traditional character, while a modern and elegant ambience is provided. \r\nFurthermore, the property disposes of a spacious apartment with living room, two bedrooms and bathroom. Outside you will find a beautifully kept Mediterranean garden and a swimming pool with surrounding sun terraces.\r\nThe property has been used as a country hotel until now.'),
('79102','27350','5',Null),
('79103','27351','5',Null),
('79104','27352','5',Null),
('79105','27353','5',Null),
('79106','27354','5',Null),
('79108','27348','22','Preciosa casa de campo en la Sierra de Tramuntana'),
('79109','27349','22','En medio del hermoso paisaje de la Sierra de Tramuntana, en un pueblo tranquilo e ídilico se encuentra esta casa de campo, que está en un perfecto estado de conservación.\r\nLa casa dispone de siete espaciosas y bien equipadas habitaciones, todas disponen de baños en suite. Las instalaciones incluyen aire acondicionado, calefacción central y televisión vía satélite.\r\nLas habitaciones están decoradas en estilo tradicional, que refleja el encanto de la antigua España. El edificio original, con dos torres morunos, fue cuidadosamente reformado por artesanos locales, manteniendo su carácter tradicional, mientras que se puede disfrutar de todas las comodidades que ofrece un diseño moderno y actual. \r\nLa propiedad incluye un amplio apartamento con salón, dos dormitorios y baño. .La zona exterior ofrece un jardín mediterráneo y una piscina rodeada de terrazas.\r\nHasta ahora ha sido utilizada como hotel rural.'),
('79110','27350','22',Null),
('79111','27351','22',Null),
('79112','27352','22',Null),
('79113','27353','22',Null),
('79114','27354','22',Null),
('79116','27356','1',Null),
('79117','27357','1',Null),
('79118','27358','1',Null),
('79119','27359','1',Null),
('79120','27357','5',Null),
('79121','27356','5',Null),
('79122','27358','5',Null),
('79123','27359','5',Null),
('79124','27357','22',Null),
('79125','27356','22',Null),
('79126','27358','22',Null),
('79127','27359','22',Null);
