/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('98955','34152','1','Beeindruckende Finca bei Llucmajor / Campos  zu verkaufen'),
('98956','34153','1','Die exzellente Neubaufinca auf Mallorca steht auf einem 17.500m² großen Grundstück und wurde 2008 mit hochwertigen Materialien erstellt. Sie bietet auf einer Wohnfläche von ca. 450m² ein Wohn-Esszimmer, Einbauküche, Hauswirtschaftsraum,  7 Schlafzimmer und 6 Badezimmer. Das Anwesen liegt in einer ruhigen und zentralen Lage nur 15 min von Palma de Mallorca entfernt. Die Finca ist ideal für eine große Familie und man hat die Möglichkeit, sie in einen 2 Familienhaushalt aufzuteilen, mit zweitem Wohnzimmer, Küche und Schlafzimmer mit  Bädern. Weitere Ausstattungsmerkmale beinhalten: Öl-Zentralheizung (Wand, Fußboden- und Deckenheizung), Handtuchtrockner, Solarpanelen mit 3000 Liter Pufferspeicher, 2 Kamine (einer davon Wasser führend mit Anschluss an die Zentralheizung. Die hochwertigen Doppelglas - Fenster haben außen einen Alu- und innen einen Holzlook.  Kühlung erfolgt über 2 Tiefenbohrungen mit Schweizer Erdsonden. Des Weiteren gibt es noch einen eignen Brunnen mit 4 Zisternen. Das Anwesen hat ein Energie Zertifikat der Klasse A und ist völlig autark. Sie besitzt eine eigne Stromversorgung über Photovoltaik und Deutz Dieselgenerator. Stromanschluss ans öffentliche Stromnetz ist möglich. Weiterhin bietet die Finca noch diverse Terrassen und einen Salzwasserpool sowie überdachte Parkplätze und eine große Garage'),
('98957','34154','1',Null),
('98958','34155','1',Null),
('98959','34156','1',Null),
('98960','34157','1',Null),
('98961','34158','1',Null),
('98963','34152','5','Impressive finca in Llucmajor / Campos for sale'),
('98964','34153','5','The excellent new finca is located on a 17.500m² large property and was created in 2008 with high quality materials. It offers a total living space of 450m² spreded over Living – Dining area, kitchen,  7 bedrooms and 6 bathrooms. The property is situated in a quiet and central location only 15 min away from Palma de Mallorca. The finca is ideal for a large family and possessing the ability to allocate them in a 2 family households, with a second living room, kitchen and bedrooms with bathrooms. Additional features include: Oil central heating (wall, floor and ceiling heating), towel rail, solar panels with 3000 liter storage tank, 2 fireplaces (one water leader with connections to the central heating. The high quality double glazed - windows have outside an aluminum and inside a wood look. The finca can be cooled down by 2 deep wells. Furthermore own water wells with 4 storage tanks. The property has an energy certificate class A and is completely self-sufficient. It has a peculiar power through photovoltaic and Deutz diesel generator. Power connection to the public grid is possible.  Moreover, teh Finca features diverse terraces, a saltwater swimming pool, covered parking places and a large garage'),
('98965','34154','5',Null),
('98966','34155','5',Null),
('98967','34156','5',Null),
('98968','34157','5',Null),
('98969','34158','5',Null),
('98971','34152','22','Impresionante finca en Llucmajor / Campos en venta'),
('98972','34153','22','El nuevo y excelente finca en Mallorca se encuentra en una gran propiedad 17.500m² y fue creado en 2008 con materiales de alta calidad. Dispone de un espacio habitable de 450m² con 7 dormitorios y 6 baños, salon-comedor, cocina y lavanderia. La propiedad está situada en una zona tranquila solo a 15 min de Palma de Mallorca. La finca es ideal para una familia grande y que posee la capacidad de asignar en una casa de 2 familias, con una habitación, cocina segundo de estar y dormitorios con baños. Las características adicionales incluyen : calefacción central de gasoil (pared-, suelo- y techo calefacción), toallero, paneles solares con acumulador de 3.000 litros, 2 chimeneas (una líder agua con conexiones con el centro de calentamiento). Ventanas de la alta calidad con doble acristalamiento. Las ventanas tienen fuera de una lata de aluminio y el interior de una madera. Enfriado por 2 pozos profundos con sondas geotérmicas. Además propia fuentede Aqua con 4 tanques. La propiedad tiene una clase de certificado de eficiencia energética „A“ y es completamente autosuficiente. Ademas tiene un poder peculiar a través fotovoltaica y Deutz diesel generador. Conexión de energía a la red pública es posible.  Por otra parte, la Finca tiene diversas terrazas, una piscina de agua salada, un aparcamiento cubierto y un amplio garaje'),
('98973','34154','22',Null),
('98974','34155','22',Null),
('98975','34156','22',Null),
('98976','34157','22',Null),
('98977','34158','22',Null),
('98979','34160','22','2008'),
('98980','34160','5','2008'),
('98981','34160','1','2008'),
('98982','34161','1',Null),
('98983','34162','1',Null),
('98984','34163','1',Null),
('98985','34164','1',Null),
('98986','34162','5',Null),
('98987','34161','5',Null),
('98988','34163','5',Null),
('98989','34164','5',Null),
('98990','34162','22',Null),
('98991','34161','22',Null),
('98992','34163','22',Null),
('98993','34164','22',Null);
