/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('98841','34106','1',' Villa in der Costa de la Calma zu verkaufen'),
('98842','34107','1','Diese gepflegte Villa liegt direkt an einer Grünzone in einer Südlage.\r\nDas Haus ist auf der Hauptwohnebene ausgestattet mit 3 Schlafzimmern, 2 Bädern, Wohnzimmer, großer und Licht durch fluteten Küche. \r\nDas Gästeapartment befindet sich auf der Poolebene und besitzt 2 Schlafzimmer, 2 Bäder, Wohnzimmer und einer Küche. Die gute Ausstattung lässt keine, wünsche offen, Klimaanlage warm/kalt, doppelt verglaste Fenster, Holzblenläden , offener Kamin, Abstellraum sowie eine Einbauküche mit Elektrogeräten. \r\n'),
('98843','34108','1',Null),
('98844','34109','1',Null),
('98845','34110','1',Null),
('98846','34111','1',Null),
('98847','34112','1',Null),
('98849','34106','5','Villa in Costa de la Calma for sale'),
('98850','34107','5','Costa de la Calma is located between Santa Ponsa and Paguera, in the southwest of Mallorca.\r\nThis well maintained villa is located directly on a green zone in a south facing position. The house has on the main level with 3 bedrooms, 2 bathrooms, living room and a large, bright kitchen. The guest apartment is located on the ground floor on the pool level and has 2 bedrooms, 2 baths, living room and kitchen. The house is very good equipment and leaves nothing to be desired. It comes with air conditioning hot / cold, double glazed windows, wooden shutters, fireplace, storage room and a fitted kitchen with electrical appliances\r\n'),
('98851','34108','5',Null),
('98852','34109','5',Null),
('98853','34110','5',Null),
('98854','34111','5',Null),
('98855','34112','5',Null),
('98857','34106','22','Villa in Costa de la Calma for sale'),
('98858','34107','22','Costa de la Calma is located between Santa Ponsa and Paguera, in the southwest of Mallorca.\r\nThis well maintained villa is located directly on a green zone in a south facing position. The house has on the main level with 3 bedrooms, 2 bathrooms, living room and a large, bright kitchen. The guest apartment is located on the ground floor on the pool level and has 2 bedrooms, 2 baths, living room and kitchen. The house is very good equipment and leaves nothing to be desired. It comes with air conditioning hot / cold, double glazed windows, wooden shutters, fireplace, storage room and a fitted kitchen with electrical appliances\r\n'),
('98859','34108','22',Null),
('98860','34109','22',Null),
('98861','34110','22',Null),
('98862','34111','22',Null),
('98863','34112','22',Null);
