/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('95801','33046','1','Neubau Villa im moderen Finca Stil, Monport, Porto Andratx'),
('95802','33047','1','Port Andratx ist eine der beliebtesten Wohnlagen auf Mallorca und der ideale Wohnort für anspruchsvolle Immobiliensuchende. Porto Andratx bietet aber nicht nur Luxusimmobilien, sondern auch ein grosse Außwahl an Top Restaurants, Cafés, einen 18 Loch Golfplatz (in Camp de Mar) und einen Jachthafen.\r\nDie hier angebotene Villa steht auf einem ca. 2.700m² großen Grundstück in der Wohnlage Monport. Von hier aus hat man einen fantastischen Blick auf die Bucht von P.Andratx und auf das Meer. Die 930m² Wohnfläche verteilt sich auf 2 Etagen. Über den Eingang im EG betritt man die Eingangshalle von der aus man das Wohnzimmer, die Küche (Miele), Hauswirtschaftsraum, Gäste WC, Esszimmer, 1 Schlafzimmer mit Ankleide und Badezimmer en suite, sowie ein Gästeapartment mit Wohn-Esszimmer, Küchenzeile, Schlafzimmer und Badezimmer.\r\nIm 1.OG befindet sich das Hauptschlafzimmer mit Salon, Ankleide und Badezimmer en Suite, Spabereich (60m²), sowie 2 weitere Schlafzimmer mit einem Salon und einem Badezimmer. Eine Garage bietet Platz für 4 Autos und ein Carport Platz für 2 Autos. Zur hochwertigen Ausstattung gehören Möbeleinrichtung, eine Ölzentralheizung (Fußboden und Radiatoren), Klimaanlage w/k, Energie-Autark-Haus: Solar, Speicher und Fotofoltaik, WIFI, Videoüberwachung, Lautsprechersystem und v.m. Im Außenbereich hat es noch einen 15mx5,5m grosse Pool mit Gegenschwimmanlage, Liegeterrassen, sowie ein angelegter Garten mit versch. Palmen, mediterrane Pflanzen und ein automatisches Bewässerungssystem. Top Villa in Top Lage.\r\n'),
('95803','33048','1',Null),
('95804','33049','1',Null),
('95805','33050','1',Null),
('95806','33051','1',Null),
('95807','33052','1',Null),
('95809','33046','5','Newly built villa finished in a modern finca style, Monport, Porto d´Andratx'),
('95810','33047','5','Port d´Andratx is one of the most popular residential areas in Mallorca, the ideal residence for demanding property seekers. Porto d´Andratx does not only offer luxury real estate, but also a large sortiment of top restaurants, cafes, a 18 hole golf course (Camp de Mar) and a marina.\r\nThe Villa offered here sits on an approximately 2,700sqm plot in the residential area Monport. From here you have a fantastic view of the bay of Porto d´Andratx and the sea. The 930m² living space is spread over 2 floors. Over the entrance on the ground floor you enter the hall from which one you reach the living room, kitchen (Miele), utility room, guest toilet, dining room, 1 bedroom with dressing room and bathroom en suite, a separate guest apartment with living room, kitchenette, bedroom and bathroom.\r\nOn the 1st floor are the master bedroom with salon, dressing room and bathroom en suite, spa area (60m²), and 2 more bedrooms with a living room and a bathroom. A garage has space for 4 cars and a carport for 2 cars. For high-quality facilities includes furniture facility, an oil central heating (floor and radiators), air conditioning h/c, inteligent house control system, solar panels, fotofoltaik, WIFI, video surveillance and many more. Outside: it still has a large pool with 15mx5,5m counter current system, sun deck and a garden with various Palm trees, mediterranean plants and an automatic irrigation system. Top villa in a great location.\r\n'),
('95811','33048','5',Null),
('95812','33049','5',Null),
('95813','33050','5',Null),
('95814','33051','5',Null),
('95815','33052','5',Null),
('95817','33046','22','Villa de nueva construcción terminó en un estilo moderno finca, Monport, Puerto d´Andratx'),
('95818','33047','22','Puerto d´Andratx es una de las zonas residenciales más populares de Mallorca, la residencia ideal para los exigentes buscadores de inmuebles. Porto Andratx no sólo ofrece inmuebles de lujo, sino también un gran surtido de los mejores restaurantes, cafés, un campo de golf de 18 hoyos (Camp de Mar) y un puerto deportivo.\r\nLa Villa ofrece aquí es sobre una 2.700m² de terreno en la zona residencial Monport. Desde aquí se tiene una vista fantástica de la bahía de Porto d´Andratx y el mar. El espacio de 930m² habitable se distribuye en 2 plantas. Sobre la entrada en la planta baja se introduce un hal d´entrada, una sala de estar, cocina (de Miele), lavadero, aseo, comedor, 1 dormitorio con vestidor y baño en suite y un apartamento de invitados con salón, cocina, dormitorio y baño.\r\nLa primera planta está el dormitorio principal con sala de estar, vestidor y cuarto de baño privado, zona de spa (60m²), y 2 más dormitorios con una sala de estar y un baño. Un garaje tiene espacio para 4 coches y una cochera para 2 coches. Para instalaciones de alta calidad incluyen instalación de muebles, una calefacción central de gasoil (suelo y radiadores), aire acondicionado f/c, sistema autocontol „casa inteligente“ para reglar:  energia solar, almacenamiento y fotofoltaik, WIFI, video vigilancia, sistema de megafonía y mucho mas. En el exterior, que todavía tiene una gran piscina 15mx5,5m con sistema de contra corriente, terrazas y jardín con varios Palms, plantas mediterráneas y un sistema de riego automático. Top villa en una gran ubicación.\r\n'),
('95819','33048','22',Null),
('95820','33049','22',Null),
('95821','33050','22',Null),
('95822','33051','22',Null),
('95823','33052','22',Null),
('95825','33054','22','2014'),
('95826','33054','5','2014'),
('95827','33054','1','2014'),
('95828','33055','1',Null),
('95829','33056','1',Null),
('95830','33057','1',Null),
('95831','33058','1',Null),
('95832','33056','5',Null),
('95833','33055','5',Null),
('95834','33057','5',Null),
('95835','33058','5',Null),
('95836','33056','22',Null),
('95837','33055','22',Null),
('95838','33057','22',Null),
('95839','33058','22',Null);
