/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('95976','33111','1','Charmante Ferienhausvilla in Abubillas Golfresort Santa Ponsa'),
('95977','33112','1','Die sehr gepflegte Villa versprüht einen besonders ausgeprägten mediterranen Charme und steht in 1. Golfplatzlinie auf einem ca. 625m² großen Grundstück. Von allen Ebenen hat man einen wunderschönen Blick in südlicher Ausrichtung auf den Golfplatz von Santa Ponsa I. Die Villenanlage Abubillas wurde Ende der 90er Jahre von Stardesigner Pedro Otzup erstellt und erfreut sich noch heute großer Beliebtheit. Abubillas ist ein Ort der Entspannung nicht nur für  Golfer, die hier einen Teil des Jahres verbringen, sondern auch bei Residenten, die das ganze Jahr hier leben. Die Villa bietet auf ca 220m² Wohnfläche, die sich wie folgt verteilt: Im EG befinden sich Eingangsdiele, Wohn-Esszimmer mit hoher Decke, offene Küche mit Bartresen, Gäste WC, 2 Schlafzimmer mit je einem Bad en suite. Über eine Außentreppe gelangt man in das 1. OG zu einem Gäste Schlafzimmer mit Bad en suite und großer Terrasse. Der mediterrane Garten wird automatisch bewässert. Ein 4x8m großer Pool mit Gegenstromanlage und ein überdachter Lounge Bereich mit Kamin und Sauna laden zum Relaxen ein. Zur guten Ausstattung gehören u.a. eine Klimaanlage w/k, elektr. Fußbodenheizung in den Bädern, Einbauküche, Kamin im Wohnzimmer, und einiges mehr.'),
('95978','33113','1',Null),
('95979','33114','1',Null),
('95980','33115','1',Null),
('95981','33116','1',Null),
('95982','33117','1',Null),
('95984','33111','5','Charming Villa in Golf Resort Abubillas, Santa Ponsa'),
('95985','33112','5','The well maintained villa exudes a particularly pronounced Mediterranean charm and is in 1st line golf course on an approximately 625m² of land. From all levels you have a wonderful view in the south orientation overlooking the golf course of Santa Ponsa I. The villa complex Abubillas was created late 90s by star designer Pedro Otzup and enjoys still great popularity today. Abubillas is a place for relaxation, not only for golfers who spend part of the year here, but also for residents who live here all year round. The villa offers approximately 220m² of living space, which is distributed as follows: The ground floor entrance hall, living-dining room with high ceilings, open kitchen with wet bar, guest toilet, 2 bedrooms with a bathroom en suite. An outside staircase leads to the 1st floor to a guest bedroom with bathroom en suite and large terrace. The Mediterranean garden is watered automatically. A 4x8m large pool with counter current system and a roofed lounge area with fireplace and sauna invite you to relax. Is well equipped with air conditioning w / c, electric., underfloor heating in the bathrooms, fitted kitchen, fireplace in living room, and more'),
('95986','33113','5',Null),
('95987','33114','5',Null),
('95988','33115','5',Null),
('95989','33116','5',Null),
('95990','33117','5',Null),
('95992','33111','22','Casa en Abubillas Golf Resort Santa Ponsa'),
('95993','33112','22','La villa bien mantenido emana se encuentra en primera línea de golf en un solar de 625m² de terreno. De todos los niveles tiene una maravillosa vista panorámica en dirección sur en el campo de golf de Santa Ponsa I. El complejo de villas Abubillas fue creado a finales de los años 90 por el diseñador estrella de Pedro Otzup y goza de gran popularidad en la actualidad. Abubillas es un lugar de relajación no sólo para los golfistas que pasan parte del año aquí, sino también para los residentes que viven aquí todo el año. La villa ofrece aprox. 220m² de superficie habitable, que se distribuye de la siguiente manera: La planta baja de vestíbulo, salón-comedor con techos altos, cocina abierta con barra de bar, aseo, 2 dormitorios con baño en suite. Una escalera exterior conduce a la primera planta de un dormitorio de invitados con baño en suite y una gran terraza. El jardín mediterráneo se riega automáticamente. Una gran piscina 4x8m con sistema de contracorriente y una sala de estar cubierta con chimenea y sauna invitan a relajarse. Está bien equipada con, entre otras cosas, aire acondicionado w / c, eléctrica, calefacción por suelo radiante en los baños, cocina equipada, chimenea en salón, y más'),
('95994','33113','22',Null),
('95995','33114','22',Null),
('95996','33115','22',Null),
('95997','33116','22',Null),
('95998','33117','22',Null),
('96000','33119','22','1996'),
('96001','33119','5','1996'),
('96002','33119','1','1996'),
('96003','33120','1',Null),
('96004','33121','1',Null),
('96005','33122','1',Null),
('96006','33123','1',Null),
('96007','33121','5',Null),
('96008','33120','5',Null),
('96009','33122','5',Null),
('96010','33123','5',Null),
('96011','33121','22',Null),
('96012','33120','22',Null),
('96013','33122','22',Null),
('96014','33123','22',Null);
