/* Uebersetzungen */
INSERT INTO Uebersetzungen (UEB_ID,UEB_NUMMER,UEB_FKID_SPR_ID,UEB_TEXT) VALUES 
('98639','34038','1','Aparthotel an der Ostküste Mallorcas zu verkaufen'),
('98640','34039','1','Dieses Aparthotel liegt in einem beliebten Badeort an der Ostküste Mallorcas. Die Anlage hat ein Mix von insgesamt 40 Apartments und Bungalows die sich auf einen 5.500m² grossen Garten Grundstück verteilen. Zur Anlage gehören noch ein Pool, 3 Ladenlokale und ein Restaurant. Die Anlage hat seit 16 Jahren einen Vertrag mit einem deutschen Reiseveranstalter mit einer Jahres Rendite von 9% auf den Kaufpreis.\r\nWeitere Infos erhalten Sie von uns bei Angabe Ihres vollen Namens, Tel Nr. und Postanschrift. Für eine Objekt Besichtigung verlangt der Verkäufer einen Bonitätsnachweis über die Kaufsumme. Bilanzen des Objektes können nach der Besichtigung eingesehen werden\r\n'),
('98641','34040','1',Null),
('98642','34041','1',Null),
('98643','34042','1',Null),
('98644','34043','1',Null),
('98645','34044','1',Null),
('98647','34038','5','Apart Hotel on the east coast of Majorca for sale'),
('98648','34039','5','This aparthotel is located in a popular seaside resort on the east coast of Mallorca. The complex has spread a mix of 40 apartments and bungalows sitting on a 5,500sqm large garden plot. The complex even has a swimming pool, 3 shops and a restaurant. The facility has a contract with a German tour operator since 16 years, with an annual return of approx 9% on the purchase price.\r\nFurther information can be obtained from us by mailing your full name, phone no., and postal address. For a property viewing the seller demands a credit proof of the purchase price. Budgets and occupacion infos of the object can be viewed after the visit\r\n'),
('98649','34040','5',Null),
('98650','34041','5',Null),
('98651','34042','5',Null),
('98652','34043','5',Null),
('98653','34044','5',Null),
('98655','34038','22','Apart Hotel en la costa este de Mallorca en venta'),
('98656','34039','22','Este aparthotel se encuentra en un popular pueblo de vacacio en la costa este de Mallorca. El complejo se ha extendido una mezcla de 40 apartamentos y bungalows en una parcela de 5.500m² gran jardín. El complejo tiene una piscina, 3 tiendas y un restaurante. Despues 16 anos hay un contracto con un operador turístico alemán con un rendimiento anual del 9% sobre el precio de compra por.\r\nMás información se puede obtener de nosotros a que contiene su nombre completo, teléfono., y dirección postal. Para una cita de visite de la propiedad, el vendedor exige una prueba de crédito del precio de compra.  Las tasas de movimiento y de ocupación se pueden verdespues visitando\r\n'),
('98657','34040','22',Null),
('98658','34041','22',Null),
('98659','34042','22',Null),
('98660','34043','22',Null),
('98661','34044','22',Null),
('98663','34046','1',Null);
